"""
Clark CLI — Foundation Model for Warehouse Optimization
Entry point: `clark` (set via pyproject.toml: clark = "cli.main:app")
Uses argparse (stdlib) — no extra deps.
"""
from __future__ import annotations

import argparse
import calendar
import os
import random
import sys
from datetime import date, timedelta
from pathlib import Path

# ── Rich (optional) ──────────────────────────────────────────────────────────

try:
    from rich.console import Console
    from rich.table import Table
    _RICH = True
    console = Console()
except ImportError:
    _RICH = False
    console = None

HEADER = "Clark — Foundation Model for Warehouse Optimization"
HEADER_LINE = "=" * len(HEADER)


def _header():
    if _RICH:
        console.print(f"\n[bold cyan]{HEADER}[/bold cyan]")
        console.print(f"[dim]{HEADER_LINE}[/dim]\n")
    else:
        print(f"\n{HEADER}")
        print(f"{HEADER_LINE}\n")


def _ok(msg: str):
    if _RICH:
        console.print(f"[bold green]{msg}[/bold green]")
    else:
        print(msg)


def _warn(msg: str):
    if _RICH:
        console.print(f"[bold yellow]  Warning: {msg}[/bold yellow]")
    else:
        print(f"  Warning: {msg}")


def _err(msg: str):
    if _RICH:
        console.print(f"[bold red]  Error: {msg}[/bold red]")
    else:
        print(f"  Error: {msg}", file=sys.stderr)


def _die(msg: str):
    _err(msg)
    sys.exit(1)


# ── Template content ──────────────────────────────────────────────────────────

def _load_template(template: str, name: str) -> str:
    """Return template YAML text with a header comment and the facility name substituted."""
    clark_root = Path(__file__).parent.parent
    template_map = {
        "small":    clark_root / "clark" / "data" / "configs" / "example_small.yaml",
        "large":    clark_root / "clark" / "data" / "configs" / "example_large.yaml",
        "full":     clark_root / "clark" / "data" / "configs" / "example_1.yaml",
    }
    path = template_map.get(template)
    if path is None or not path.exists():
        _die(f"Template '{template}' not found at {path}.")

    text = path.read_text(encoding="utf-8")

    # Swap facility name into the `facility:` block's name field. Scoped
    # rewrite so it can't accidentally hit a `name:` line inside the worker
    # roster that happens to match the template's facility name string.
    lines = text.splitlines(keepends=True)
    in_facility_block = False
    for i, line in enumerate(lines):
        if line.startswith("facility:"):
            in_facility_block = True
            continue
        if in_facility_block:
            # End of block when we hit a non-indented, non-blank line
            if line and not line[0].isspace() and line.strip():
                break
            stripped = line.strip()
            if stripped.startswith("name:"):
                indent = line[: len(line) - len(line.lstrip())]
                lines[i] = f'{indent}name: "{name}"\n'
                break
    text = "".join(lines)

    header_comment = "# Generated by 'clark init' — fill in your real values\n"
    return header_comment + text


# ── Commands ──────────────────────────────────────────────────────────────────

def cmd_init(args: argparse.Namespace):
    _header()
    output_path = Path(args.output_path)

    print("Scaffolding a new facility config...\n")

    # Prompt: facility name
    try:
        name = input("Facility name: ").strip()
        if not name:
            name = "My Warehouse"
    except (EOFError, KeyboardInterrupt):
        name = "My Warehouse"

    # Prompt: number of workers (informational)
    try:
        input("Approximate number of workers: ").strip()
    except (EOFError, KeyboardInterrupt, ValueError):
        pass

    # Prompt: template
    try:
        tmpl_input = input("Start from template? [small/large/full] (default: small): ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        tmpl_input = ""

    tmpl = tmpl_input if tmpl_input in ("small", "large", "full") else "small"

    content = _load_template(tmpl, name)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    _ok(f"Config written to: {output_path}")
    print(f"Template: {tmpl}")
    print("Edit the file to match your facility's real values, then run:")
    print(f"  clark validate {output_path}")


def cmd_validate(args: argparse.Namespace):
    _header()
    config_path = Path(args.config_path)

    if not config_path.exists():
        _die(f"Config file not found: {config_path}")

    try:
        from clark.config.schema import FacilityConfig
        config = FacilityConfig.from_yaml(config_path)
    except Exception as e:
        _die(f"Failed to load config: {e}")

    errors, warnings = config.validate()

    # Volume summary: find overall min/max across all months
    all_lows = [v[0] for v in config.volume.seasonal_ranges.values()]
    all_highs = [v[1] for v in config.volume.seasonal_ranges.values()]
    vol_lo = min(all_lows) if all_lows else 0
    vol_hi = max(all_highs) if all_highs else 0

    print(f"  Name:         {config.name}")
    print(f"  Workers:      {config.num_workers}")
    print(f"  Tasks:        {config.num_tasks}  ({', '.join(config.task_ids)})")
    print(f"  Volume range: {vol_lo}–{vol_hi} orders/day")
    print()

    if errors:
        for e in errors:
            _err(e)
        print()
    if warnings:
        for w in warnings:
            _warn(w)
        print()

    if errors:
        _err(f"Config has {len(errors)} blocking error(s). Fix before training.")
        sys.exit(1)
    else:
        _ok("Config is valid!")


def cmd_pretrain(args: argparse.Namespace):
    _header()
    print(f"Starting pre-training: {args.episodes} episodes")
    print(f"Output: {args.output}")
    print()

    # Auto log-interval: batched runs complete episodes in chunks of n_envs at
    # a time, so a lower number keeps the screen updating.
    log_interval = args.log_interval
    if log_interval == 0:
        log_interval = 4 if args.n_envs > 1 else 10

    try:
        if args.n_envs > 1:
            from clark.training.pretrain import pretrain_batched
            pretrain_batched(
                n_episodes=args.episodes,
                n_envs=args.n_envs,
                output_path=args.output,
                save_interval=args.save_interval,
                log_interval=log_interval,
                device=args.device,
                use_amp=not args.no_amp,
                compile_model=args.compile,
                use_mp=args.mp,
                years_per_config=args.years_per_config,
            )
        else:
            from clark.training.pretrain import pretrain
            pretrain(
                n_episodes=args.episodes,
                output_path=args.output,
                save_interval=args.save_interval,
                log_interval=log_interval,
                device=args.device,
                use_amp=not args.no_amp,
                compile_model=args.compile,
                years_per_config=args.years_per_config,
            )
    except KeyboardInterrupt:
        print("\nPre-training interrupted.")
        sys.exit(1)
    except Exception as e:
        _die(f"Pre-training failed: {e}")


def cmd_finetune(args: argparse.Namespace):
    _header()

    config_path = Path(args.config)
    base_path = Path(args.base)

    if not config_path.exists():
        _die(f"Config not found: {config_path}")
    if not base_path.exists():
        _die(f"Base checkpoint not found: {base_path}")

    print(f"Fine-tuning on config: {config_path}")
    print(f"Base model:            {base_path}")
    print(f"Output:                {args.output}")
    print(f"Episodes: {args.episodes}  LR: {args.lr}  freeze-encoder: {args.freeze_encoder}")
    print()

    # Resolve --save-interval=0 to the auto-picked default. ceil-style
    # divide-by-3 so a 5-episode run saves at ep 2 + ep 4 + final
    # (not just at the very end), and a 50-episode run still saves
    # every 10 — matches the prior behavior at the long-run end.
    eff_save_interval = args.save_interval
    if eff_save_interval == 0:
        eff_save_interval = max(1, min(10, args.episodes // 3))
        print(f"  [auto] --save-interval not set; using {eff_save_interval} "
              f"(episodes={args.episodes} // 3, clamped to [1, 10])")

    try:
        from clark.training.finetune import finetune
        finetune(
            config_path=str(config_path),
            base_model_path=str(base_path),
            output_path=args.output,
            n_episodes=args.episodes,
            lr=args.lr,
            freeze_encoder=args.freeze_encoder,
            save_interval=eff_save_interval,
            log_dir=args.log_dir,
        )
    except KeyboardInterrupt:
        print("\nFine-tuning interrupted.")
        sys.exit(1)
    except Exception as e:
        # Print the full traceback BEFORE _die — `str(e)` alone
        # loses the call-site context, which the wizard's subprocess
        # log needs to diagnose CUDA / module-load failures.
        import traceback as _tb
        _tb.print_exc()
        _die(f"Fine-tuning failed: {e}")


# These two helpers were inlined here historically; the server
# (clark/serve/app.py) imported them across the CLI layering
# boundary. They now live in clark.inference.plan; re-exported
# under their old leading-underscore names so any external script
# that imported the private symbols continues to work.
from clark.inference.plan import (
    run_one_plan_day as _run_one_plan_day,
    sample_volume_for_date as _sample_volume_for_date,
)



def cmd_plan(args: argparse.Namespace):
    _header()

    config_path = Path(args.config)
    model_path = Path(args.model)

    if not config_path.exists():
        _die(f"Config not found: {config_path}")
    if not model_path.exists():
        _die(f"Model checkpoint not found: {model_path}")

    # Parse date
    try:
        if args.date:
            start_date = date.fromisoformat(args.date)
        else:
            start_date = date.today()
    except ValueError:
        _die(f"Invalid date format: {args.date!r}. Use YYYY-MM-DD.")

    try:
        from clark.config.schema import FacilityConfig
        config = FacilityConfig.from_yaml(config_path)
    except Exception as e:
        _die(f"Failed to load config: {e}")

    try:
        from clark.agent.ppo import ClarkAgent
        agent = ClarkAgent.load(str(model_path))
    except Exception as e:
        _die(f"Failed to load model: {e}")

    days_ahead = max(1, args.days)

    for day_offset in range(days_ahead):
        target_date = start_date + timedelta(days=day_offset)

        # Skip weekend days the facility doesn't operate.
        _wd = target_date.weekday()
        if _wd == 5 and not config.rules.work_saturday:
            continue
        if _wd == 6 and not config.rules.work_sunday:
            continue

        volume, vol_label = _sample_volume_for_date(config, target_date)
        day_name = calendar.day_name[target_date.weekday()]
        date_str = target_date.strftime("%Y-%m-%d")

        try:
            assignments = _run_one_plan_day(config, agent, target_date, volume)
        except Exception as e:
            _die(f"Failed to generate plan for {date_str}: {e}")

        if _RICH:
            title = f"Shift Plan: {day_name} {date_str}"
            border_len = max(len(title) + 4, 46)
            top_border = "╔" + "═" * (border_len - 2) + "╗"
            bot_border = "╚" + "═" * (border_len - 2) + "╝"

            console.print(f"\n[bold cyan]{top_border}[/bold cyan]")
            console.print(f"[bold cyan]║[/bold cyan] [bold]{title}[/bold]")
            console.print(f"[bold cyan]║[/bold cyan] Forecast: ~{volume} orders ([italic]{vol_label}[/italic])")
            console.print(f"[bold cyan]║[/bold cyan]")

            table = Table(show_header=True, header_style="bold", box=None,
                          padding=(0, 1), show_edge=False)
            table.add_column("Worker", min_width=14)
            table.add_column("Task", min_width=16)
            table.add_column("Hustle", min_width=6)

            for worker_name, task_name, hustle in assignments:
                hustle_str = "[green]Yes[/green]" if hustle else "No"
                table.add_row(worker_name, task_name.replace("_", " ").title(), hustle_str)

            console.print(table)
            console.print(f"[bold cyan]{bot_border}[/bold cyan]")
        else:
            title = f"Shift Plan: {day_name} {date_str}"
            border_len = max(len(title) + 4, 46)
            top_border = "╔" + "═" * (border_len - 2) + "╗"
            bot_border = "╚" + "═" * (border_len - 2) + "╝"

            print(f"\n{top_border}")
            print(f"║ {title}")
            print(f"║ Forecast: ~{volume} orders ({vol_label})")
            print(f"║")
            print(f"║ {'Worker':<14} | {'Task':<16} | Hustle")
            print(f"║ {'-'*14}-+-{'-'*16}-+-------")
            for worker_name, task_name, hustle in assignments:
                task_display = task_name.replace("_", " ").title()
                hustle_str = "Yes" if hustle else "No"
                print(f"║ {worker_name:<14} | {task_display:<16} | {hustle_str}")
            print(f"{bot_border}")


def cmd_ops(args: argparse.Namespace):
    """Operations dashboard — forms over clark serve. Separate from
    cmd_dashboard (training metrics); this is the operator-facing UI
    for plan/what-if/compare/sweep/calendar/briefing without an LLM
    in the loop.

    The page is a single static HTML file; it talks directly to clark
    serve on :8000 from the browser (same-origin not required, both
    are localhost). No server-side logic needed beyond serving the
    file, so this is a 30-line stdlib HTTP server.
    """
    _header()
    page = (Path(__file__).parent.parent / "clark" / "ops" / "index.html")
    if not page.exists():
        _die(f"Ops dashboard HTML not found at {page}")

    import http.server
    import json as _json
    import socket as _socket
    import subprocess as _subprocess
    import time as _time
    import webbrowser

    WIZARD_PORT = 8090

    def _port_open(host: str, port: int, timeout: float = 0.4) -> bool:
        s = _socket.socket(_socket.AF_INET, _socket.SOCK_STREAM)
        s.settimeout(timeout)
        try:
            s.connect((host, port))
            return True
        except OSError:
            return False
        finally:
            s.close()

    def _launch_wizard_subprocess():
        """Spawn `clark wizard` in a new console window if it isn't
        already serving on :8090. Returns (ok: bool, message: str).
        Mirrors clark-mcp/clark_mcp/web/server.py:_launch_wizard so
        the New facility button on the dashboard has the same UX as
        the chat's wizard launch."""
        if _port_open("127.0.0.1", WIZARD_PORT):
            return True, "already running"
        try:
            if os.name == "nt":
                # New console window so the user can see the wizard's
                # logs and close it independently of the dashboard.
                CREATE_NEW_CONSOLE = 0x00000010
                _subprocess.Popen(
                    [sys.executable, "-m", "cli.main", "wizard"],
                    creationflags=CREATE_NEW_CONSOLE,
                    close_fds=True,
                    cwd=str(Path(__file__).parent.parent),
                )
            else:
                _subprocess.Popen(
                    [sys.executable, "-m", "cli.main", "wizard"],
                    start_new_session=True,
                    stdout=_subprocess.DEVNULL,
                    stderr=_subprocess.DEVNULL,
                    cwd=str(Path(__file__).parent.parent),
                )
        except Exception as e:
            return False, f"couldn't spawn `clark wizard`: {type(e).__name__}: {e}"
        # Poll for bind
        deadline = _time.time() + 20.0
        while _time.time() < deadline:
            if _port_open("127.0.0.1", WIZARD_PORT):
                return True, "launched"
            _time.sleep(0.4)
        return False, ("Wizard launched but didn't bind on :8090 within "
                       "20s. Check the new console window for errors.")

    def _list_training_runs():
        """Scan the per-facility log dirs the trainer writes to and
        return a summary per run for the dashboard's Training tab.
        Source paths:
          clark/data/checkpoints/user/logs_<facility>/training_metrics.json
          clark/data/logs/pretrain/training_metrics.json (foundation)
        We don't gate by 'alive' — finished runs are still useful to
        see (final episode count, total time, etc.).
        """
        repo_root = Path(__file__).parent.parent
        candidates = []
        # Per-facility fine-tune log dirs
        ckpt_user = repo_root / "clark" / "data" / "checkpoints" / "user"
        if ckpt_user.is_dir():
            for d in ckpt_user.iterdir():
                if d.is_dir() and d.name.startswith("logs_"):
                    mp = d / "training_metrics.json"
                    if mp.exists():
                        candidates.append((d.name[len("logs_"):], mp))
        # Foundation pretrain log dir (optional)
        pretrain_mp = repo_root / "clark" / "data" / "logs" / "pretrain" / "training_metrics.json"
        if pretrain_mp.exists():
            candidates.append(("foundation", pretrain_mp))

        import time as _t
        out = []
        for name, mp in candidates:
            try:
                data = _json.loads(mp.read_text(encoding="utf-8"))
            except Exception as e:
                out.append({"name": name, "path": str(mp), "error": str(e)})
                continue
            status = data.get("status") or {}
            episodes = data.get("episodes") or []
            # "alive" is only trustworthy if the trainer's heartbeat
            # is recent — the trainer sets alive=False on clean exit
            # but a hard crash leaves it True. Cross-check heartbeat
            # age: if last_heartbeat is >120s old, treat as not-alive.
            last_hb = status.get("last_heartbeat") or 0
            stale = (_t.time() - last_hb) > 120 if last_hb else True
            alive = bool(status.get("alive")) and not stale
            cur = int(status.get("current_episode", 0))
            tgt = int(status.get("n_episodes_target", 0)) or None
            elapsed = float(status.get("elapsed_s", 0))
            # ETA: per-episode wall time × remaining episodes
            eta_s = None
            if alive and cur > 0 and tgt and elapsed > 0:
                per_ep = elapsed / cur
                eta_s = max(0, int(per_ep * (tgt - cur)))
            # Recent reward (last episode's reward if present)
            last_reward = None
            if episodes:
                e = episodes[-1]
                last_reward = e.get("avg_reward") or e.get("reward")
            out.append({
                "name": name,
                "path": str(mp),
                "alive": alive,
                "stale_heartbeat": stale,
                "current_episode": cur,
                "n_episodes_target": tgt,
                "elapsed_s": elapsed,
                "eta_s": eta_s,
                "last_reward": last_reward,
                "last_heartbeat_age_s": int(_t.time() - last_hb) if last_hb else None,
                "mtime": int(mp.stat().st_mtime),
            })
        # Most recent first
        out.sort(key=lambda r: r.get("mtime", 0), reverse=True)
        return {"runs": out}

    class OpsHandler(http.server.BaseHTTPRequestHandler):
        def log_message(self, fmt, *a):
            pass

        def _send_json(self, code: int, obj):
            body = _json.dumps(obj).encode("utf-8")
            self.send_response(code)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self):
            from urllib.parse import urlparse
            path = urlparse(self.path).path
            if path in ("/", "/index.html"):
                body = page.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            elif path == "/training_runs":
                self._send_json(200, _list_training_runs())
            else:
                self.send_response(404)
                self.end_headers()
                self.wfile.write(b"Not found")

        def do_POST(self):
            from urllib.parse import urlparse
            path = urlparse(self.path).path
            if path == "/launch_wizard":
                ok, msg = _launch_wizard_subprocess()
                self._send_json(200 if ok else 500,
                                {"ok": ok, "message": msg,
                                 "url": f"http://127.0.0.1:{WIZARD_PORT}/"})
            else:
                self.send_response(404)
                self.end_headers()
                self.wfile.write(b"Not found")

    server = http.server.HTTPServer(("127.0.0.1", args.port), OpsHandler)
    url = f"http://127.0.0.1:{args.port}/"
    print(f"Clark operations dashboard -> {url}")
    print("(Talks directly to clark serve on :8000. If clark serve isn't running, "
          "the page will show 'clark serve unreachable' in the header.)")
    if not getattr(args, "no_browser", False) and \
            os.environ.get("CLARK_NO_BROWSER") != "1":
        try:
            webbrowser.open(url)
        except Exception:
            pass
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping ops dashboard.")
        server.shutdown()


def cmd_dashboard(args: argparse.Namespace):
    _header()

    log_dir = Path(args.log_dir).resolve()
    port = args.port
    dashboard_html = Path(__file__).parent.parent / "clark" / "dashboard" / "dashboard.html"

    if not dashboard_html.exists():
        _die(f"Dashboard HTML not found at {dashboard_html}")

    if not log_dir.exists():
        _warn(f"Log directory does not exist yet: {log_dir}")
        _warn("Dashboard will show no data until training produces logs.")

    import http.server
    import threading
    import webbrowser

    class DashboardHandler(http.server.BaseHTTPRequestHandler):
        def log_message(self, fmt, *a):
            pass  # suppress default access log spam

        def do_GET(self):
            from urllib.parse import urlparse
            path = urlparse(self.path).path

            if path in ("/", "/index.html"):
                # Re-read on every request so editing the HTML during a run
                # takes effect on next browser refresh — no need to restart
                # the server. Cheap (~2KB file, OS page-cached).
                self._send(200, "text/html; charset=utf-8", dashboard_html.read_bytes())
            elif path in ("/data/year_snapshot.json", "/clark/data/year_snapshot.json"):
                self._serve_json("year_snapshot.json")
            elif path == "/data/episode_log.json":
                self._serve_json("episode_log.json")
            elif path == "/data/training_metrics.json":
                self._serve_json("training_metrics.json")
            elif path == "/status":
                # Tiny lightweight endpoint — dashboard uses this for the
                # live-pill liveness check without paying the cost of a
                # full training_metrics.json fetch.
                self._serve_status()
            else:
                self._send(404, "text/plain", b"Not found")

        def _serve_status(self):
            import json as _json
            fpath = log_dir / "training_metrics.json"
            payload = {"alive": False, "current_episode": 0}
            if fpath.exists():
                try:
                    data = _json.loads(fpath.read_text())
                    payload = data.get("status", payload)
                except Exception:
                    pass
            self._send(200, "application/json",
                       _json.dumps(payload).encode("utf-8"))

        def _serve_json(self, filename: str):
            fpath = log_dir / filename
            if fpath.exists():
                try:
                    data = fpath.read_bytes()
                    self._send(200, "application/json", data)
                except Exception:
                    self._send(500, "text/plain", b"Error reading file")
            else:
                # Return empty valid structure so dashboard doesn't error out
                self._send(200, "application/json",
                           b'{"episodes":[],"training_stats":{},"year_summary":{}}')

        def _send(self, code: int, ctype: str, body: bytes):
            self.send_response(code)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            # No wildcard CORS — these servers are localhost-only and
            # same-origin in normal use. Wildcard '*' would let any
            # web page in the user's browser read responses.
            self.end_headers()
            self.wfile.write(body)

    server = http.server.HTTPServer(("localhost", port), DashboardHandler)

    url = f"http://localhost:{port}"
    print(f"  Dashboard: {url}")
    print(f"  Log dir:   {log_dir}")
    print(f"  Auto-refreshes every 10s while training is running.")
    print(f"  Press Ctrl+C to stop.\n")

    # Open browser after a short delay — unless CLARK_NO_BROWSER=1
    # (set by tests / headless / scripted launches to avoid
    # spamming the user with N tabs).
    if os.environ.get("CLARK_NO_BROWSER") != "1":
        def _open():
            import time
            time.sleep(0.5)
            webbrowser.open(url)
        threading.Thread(target=_open, daemon=True).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nDashboard stopped.")


# ── Argument parser ───────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="clark",
        description=HEADER,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")
    sub.required = True

    # init
    p_init = sub.add_parser("init", help="Scaffold a new facility config YAML.")
    p_init.add_argument("output_path", metavar="OUTPUT_PATH",
                        help="Path to write the new YAML config.")

    # validate
    p_val = sub.add_parser("validate", help="Load and validate a facility config.")
    p_val.add_argument("config_path", metavar="CONFIG_PATH",
                       help="Path to the facility YAML config.")

    # pretrain
    p_pre = sub.add_parser("pretrain", help="Pre-train the Clark foundation model.")
    p_pre.add_argument("--episodes", type=int, default=10000,
                       help="Number of training episodes (default: 10000).")
    p_pre.add_argument("--output", type=str,
                       default="clark/data/checkpoints/clark_foundation.pt",
                       help="Output checkpoint path.")
    p_pre.add_argument("--log-interval", type=int, default=0,
                       help="Print progress every N episodes "
                            "(0 = auto: 4 batched, 10 single-env).")
    p_pre.add_argument("--save-interval", type=int, default=100,
                       help="Save checkpoint every N episodes (default: 100).")
    p_pre.add_argument("--device", type=str, default="cpu",
                       help="torch device: 'cpu', 'cuda', 'cuda:0', etc. "
                            "(default: cpu).")
    p_pre.add_argument("--n-envs", type=int, default=1,
                       help="Parallel envs for batched pretrain. 1 = single-env, "
                            ">1 = batched (default: 1).")
    p_pre.add_argument("--no-amp", action="store_true",
                       help="Disable bf16 autocast on CUDA (default: enabled).")
    p_pre.add_argument("--compile", action="store_true",
                       help="torch.compile the model (~30s warmup, then faster). "
                            "Requires Triton; not supported on Windows.")
    p_pre.add_argument("--mp", action="store_true",
                       help="Use a multiprocess env runner (one OS process per env). "
                            "Big speedup when env-stepping is the bottleneck.")
    p_pre.add_argument("--years-per-config", type=int, default=5,
                       help="Train this many simulated years on each generated "
                            "facility config before sampling a new one (default: 5).")

    # finetune
    p_ft = sub.add_parser("finetune", help="Fine-tune from a foundation checkpoint.")
    p_ft.add_argument("--config", required=True,
                      help="Path to facility YAML config.")
    p_ft.add_argument("--base", required=True,
                      help="Path to the foundation checkpoint (.pt).")
    p_ft.add_argument("--output", default="clark/data/checkpoints/finetuned.pt",
                      help="Output path for fine-tuned checkpoint.")
    p_ft.add_argument("--episodes", type=int, default=500,
                      help="Number of fine-tuning episodes (default: 500).")
    p_ft.add_argument("--lr", type=float, default=5e-5,
                      help="Learning rate (default: 5e-5).")
    p_ft.add_argument("--freeze-encoder", action="store_true",
                      help="Freeze encoder layers (prevents catastrophic forgetting).")
    # save-interval = 0 means "auto-pick from --episodes": ceil(episodes/3)
    # capped at 10, floor 1. Keeps small runs (--episodes 5 → save every 2)
    # checkpointing usefully often without spamming saves on long runs.
    p_ft.add_argument("--save-interval", type=int, default=0,
                      help="Checkpoint every N episodes. 0 (default) = auto-"
                           "pick based on --episodes (max(1, min(10, "
                           "episodes // 3))), so small runs save more "
                           "frequently. Pass an explicit int to override.")
    p_ft.add_argument("--log-dir", default=None,
                      help="Where to write training_metrics.json + episode "
                           "logs. Default: a 'logs_<facility>' dir next to "
                           "--output. The wizard points this at the job dir so "
                           "progress polling reads from one known location.")

    # plan
    p_plan = sub.add_parser("plan", help="Generate a shift plan using a trained model.")
    p_plan.add_argument("--config", required=True,
                        help="Path to facility YAML config.")
    p_plan.add_argument("--model", required=True,
                        help="Path to model checkpoint (.pt).")
    p_plan.add_argument("--date", default=None,
                        help="Start date in YYYY-MM-DD format (default: today).")
    p_plan.add_argument("--days", type=int, default=1,
                        help="Number of days to plan ahead (default: 1).")

    # eval (held-out evaluation over synthetic facilities)
    p_eval = sub.add_parser("eval", help="Evaluate a checkpoint on held-out "
                                          "synthetic facilities (full-year sim, "
                                          "production grader, metric distributions).")
    p_eval.add_argument("--model", default="clark/data/checkpoints/clark_foundation.pt",
                        help="Path to the checkpoint to evaluate.")
    p_eval.add_argument("--n-per-stage", type=int, default=10,
                        help="Held-out facilities sampled per curriculum stage (default: 10).")
    p_eval.add_argument("--stages", default="1,2,3",
                        help="Comma-separated curriculum stages to evaluate (default: 1,2,3).")
    p_eval.add_argument("--seed", type=int, default=0,
                        help="Base seed for config sampling + sim (reproducible).")
    p_eval.add_argument("--device", default="cpu", help="torch device (default: cpu).")
    p_eval.add_argument("--baseline", choices=["heuristic", "greedy"], default=None,
                        help="Evaluate a non-RL baseline instead of --model "
                             "(same facilities + grader + masks). 'heuristic' "
                             "(alias 'greedy') = bottleneck-priority rule-based "
                             "scheduler, for Clark-vs-classical comparison.")
    p_eval.add_argument("--json", default=None,
                        help="Optional path to also write the full results as JSON.")

    # dashboard
    p_dash = sub.add_parser("dashboard", help="Launch the Clark training dashboard.")
    p_dash.add_argument("--log-dir", default="clark/data/logs/pretrain",
                        help="Directory containing episode_log.json / year_snapshot.json.")
    p_dash.add_argument("--port", type=int, default=8080,
                        help="Port to serve the dashboard on (default: 8080).")

    # ops (operations dashboard — forms over clark serve, no LLM)
    p_ops = sub.add_parser("ops", help="Launch the operations dashboard "
                                        "(plan / what-if / compare / sweep "
                                        "/ calendar / briefing — direct UI "
                                        "over clark serve, no LLM in the loop).")
    p_ops.add_argument("--port", type=int, default=8092,
                       help="Port to serve the ops dashboard on (default: 8092).")
    p_ops.add_argument("--no-browser", action="store_true",
                       help="Don't auto-open a browser tab.")

    # wizard
    p_wiz = sub.add_parser("wizard", help="Launch the facility setup wizard (web UI).")
    p_wiz.add_argument("--port", type=int, default=8090,
                       help="Port to serve the wizard on (default: 8090).")
    p_wiz.add_argument("--sessions-dir", default="clark/data/configs/user/sessions",
                       help="Directory for saved wizard sessions.")

    p_srv = sub.add_parser("serve", help="Run the minimal local Clark inference API (localhost only).")
    p_srv.add_argument("--model", required=True,
                       help="Path to a trained Clark checkpoint (.pt).")
    p_srv.add_argument("--facilities-dir", default="clark/data/configs",
                       help="Directory of facility config YAMLs to serve.")
    p_srv.add_argument("--port", type=int, default=8000,
                       help="Port (bound to 127.0.0.1 only; default 8000).")

    # mcp (Model Context Protocol stdio server — lets any MCP host
    # like Claude Desktop / Cursor / Continue / Zed drive Clark in
    # natural language using its own model)
    sub.add_parser("mcp",
                   help="Run the MCP stdio server (Claude Desktop, "
                        "Cursor, Continue, Zed, etc.). Wraps clark "
                        "serve; CLARK_API_URL controls the target "
                        "(default http://127.0.0.1:8000).")

    return parser


# ── MCP server (stdio) ───────────────────────────────────────────────────────

def cmd_mcp(args: argparse.Namespace):
    """Run the Model Context Protocol stdio server.

    Lets any MCP-aware host (Claude Desktop, Cursor, Continue, Zed,
    ...) drive Clark in natural language using its own model. This
    process speaks MCP on stdin/stdout; it does NOT host an LLM
    itself. Every tool delegates to a localhost `clark serve` over
    HTTP (CLARK_API_URL, default http://127.0.0.1:8000), so
    `clark serve` must already be running with a trained checkpoint.

    Wire it up by adding to the host's MCP config, e.g. for Claude
    Desktop (~/Library/Application Support/Claude/claude_desktop_config.json
    on macOS, %APPDATA%/Claude/claude_desktop_config.json on Windows):

        {"mcpServers": {"clark": {
            "command": "clark", "args": ["mcp"],
            "env": {"CLARK_API_URL": "http://127.0.0.1:8000"}
        }}}
    """
    try:
        from clark.mcp.server import main as _mcp_main
    except SystemExit:
        # The server module raises SystemExit with a clean message
        # when the `mcp` package isn't installed; re-raise.
        raise
    except ImportError as e:
        _die(f"Failed to load MCP server: {e}. "
             f"Install with: pip install -e \".[mcp]\"")
    _mcp_main()


# ── Serve (minimal local inference API) ───────────────────────────────────────

def cmd_serve(args: argparse.Namespace):
    """Run the minimal local Clark inference API. Localhost only,
    stateless, weights loaded once. See clark/serve/app.py + NOTE.md."""
    model_path = Path(args.model)
    if not model_path.exists():
        _die(f"Model checkpoint not found: {model_path}")
    fdir = Path(args.facilities_dir)
    if not fdir.is_dir():
        _die(f"Facilities dir not found: {fdir}")

    try:
        from clark.agent.ppo import ClarkAgent
        agent = ClarkAgent.load(str(model_path))      # weights loaded ONCE
    except Exception as e:
        _die(f"Failed to load model: {e}")

    try:
        import uvicorn
        from clark.serve.app import build_app
    except ImportError:
        _die("serve deps missing — install with: pip install -e \".[serve]\"")

    app = build_app(agent, fdir, checkpoint_label=model_path.name)
    print(f"Clark local inference API -> http://127.0.0.1:{args.port}  "
          f"(facilities: {fdir}, model: {model_path.name})", flush=True)
    # 127.0.0.1 ONLY — never 0.0.0.0. Local single-user by design.
    uvicorn.run(app, host="127.0.0.1", port=args.port, log_level="info")


# ── Wizard ────────────────────────────────────────────────────────────────────

def cmd_wizard(args: argparse.Namespace):
    """Launch the facility setup wizard — a local web UI that walks
    a warehouse operator through fine-tune config creation.

    Endpoints:
      GET  /                 — wizard HTML
      GET  /presets          — archetype + question library JSON
      GET  /sessions         — list saved sessions
      GET  /sessions/{id}    — load one session
      POST /sessions         — create or update a session
      POST /validate         — defensive validation on the combined config
    """
    _header()

    import http.server
    import json as _json
    import os
    import threading
    import uuid
    import webbrowser
    from datetime import datetime, timezone
    from urllib.parse import urlparse

    wizard_dir = Path(__file__).parent.parent / "clark" / "wizard"
    index_html = wizard_dir / "index.html"
    presets_path = wizard_dir / "presets.json"
    sessions_dir = Path(args.sessions_dir).resolve()
    port = args.port

    if not index_html.exists():
        _die(f"Wizard HTML not found at {index_html}")
    if not presets_path.exists():
        _die(f"Wizard presets not found at {presets_path}")

    sessions_dir.mkdir(parents=True, exist_ok=True)

    # Pre-load presets at startup to fail fast on JSON errors.
    try:
        _presets = _json.loads(presets_path.read_text(encoding="utf-8"))
    except Exception as e:
        _die(f"Failed to parse presets.json: {e}")

    def _validate_config(cfg: dict) -> dict:
        """Defensive validation — walk validation_rules from presets.json
        and report errors/warnings on the combined config. Pure Python,
        no external deps.

        The user explicitly asked for this safety net: combinations of
        preset answers can produce weird weight combos (e.g. OT-cost
        dominating shipping reward → agent prefers leaving orders unshipped).
        These rules catch those before fine-tuning burns hours.
        """
        weights = cfg.get("resulting_weights", {}) or {}
        issues = []

        for rule in _presets.get("validation_rules", []):
            check = rule.get("check")
            level = rule.get("level", "warning")
            msg = rule.get("message", "")

            if check == "per_order_shipped_gt_zero":
                if weights.get("per_order_shipped", 0) <= 0:
                    issues.append({"level": level, "rule": rule["id"], "message": msg})

            elif check == "ot_cost_vs_incomplete":
                ot_hr = abs(weights.get("per_ot_hour", 0))
                inc_pen = abs(weights.get("per_order_incomplete", 0))
                # Heuristic: if 1 hour of OT costs > 0.5x a single incomplete order,
                # the agent will sometimes prefer leaving orders incomplete.
                # The 0.5 factor is conservative — adjust based on observed behavior.
                if inc_pen > 0 and ot_hr > inc_pen * 0.5:
                    issues.append({"level": level, "rule": rule["id"], "message": msg})

            elif check == "idle_not_negative":
                if weights.get("per_idle_hour", 0) >= 0:
                    issues.append({"level": level, "rule": rule["id"], "message": msg})

            elif check == "any_weight_extreme":
                extreme = [(k, v) for k, v in weights.items() if abs(v) > 500]
                if extreme:
                    detail = ", ".join(f"{k}={v}" for k, v in extreme)
                    issues.append({
                        "level": level, "rule": rule["id"],
                        "message": f"{msg} Flagged: {detail}",
                    })

        return {"issues": issues, "checked": len(_presets.get("validation_rules", []))}

    # Roots used by generate + train endpoints
    repo_root = Path(__file__).parent.parent.resolve()
    user_configs_dir = repo_root / "clark" / "data" / "configs" / "user"
    user_checkpoints_dir = repo_root / "clark" / "data" / "checkpoints" / "user"
    user_logs_dir = repo_root / "clark" / "data" / "logs" / "user"
    user_configs_dir.mkdir(parents=True, exist_ok=True)
    user_checkpoints_dir.mkdir(parents=True, exist_ok=True)
    user_logs_dir.mkdir(parents=True, exist_ok=True)

    # In-process registry of training jobs spawned via /train/start.
    # Maps job_id → {pid, config_path, log_dir, started_at}.
    # Lost on server restart by design — training itself is durable
    # (checkpoint + log files on disk) and can be re-attached via the
    # dashboard pointing at log_dir.
    training_jobs: dict = {}
    # Parallel registry of the live Popen handles, keyed by job_id. Kept
    # separate from training_jobs because a Popen isn't JSON-serializable
    # (training_jobs gets returned in API responses). Used for a reliable,
    # signal-free liveness check via proc.poll().
    training_procs: dict = {}

    def _job_alive(job_id: str, pid: int) -> bool:
        """Is this training subprocess still running?

        IMPORTANT: do NOT use os.kill(pid, 0) on Windows — there, signal 0
        is CTRL_C_EVENT, so os.kill(pid, 0) *sends a Ctrl-C* to the pid's
        process group instead of harmlessly probing liveness. That is what
        used to kill freshly-started trainers on the very first status poll.
        Prefer the Popen handle (proc.poll()); fall back to a signal-free
        OS query for jobs spawned by a previous server instance.
        """
        proc = training_procs.get(job_id)
        if proc is not None:
            return proc.poll() is None
        if os.name == "nt":
            try:
                import subprocess as _sp2
                out = _sp2.run(
                    ["tasklist", "/FI", f"PID eq {pid}", "/NH"],
                    capture_output=True, text=True, timeout=5)
                return str(pid) in out.stdout
            except Exception:
                return False
        else:
            try:
                os.kill(pid, 0)
                return True
            except OSError:
                return False

    def _safe_filename(name: str) -> str:
        """Slugify a facility name into a filesystem-safe stem."""
        cleaned = "".join(c if c.isalnum() or c in ("-", "_") else "_"
                          for c in name.strip().lower().replace(" ", "_"))
        return cleaned.strip("_") or "facility"

    def _generate_yaml(cfg: dict) -> dict:
        """Materialize a full FacilityConfig YAML from the wizard's
        archetype + answers. Strategy: load the archetype's base
        template, then in this order overlay anything the user provided:
          - facility.name (always)
          - rewards (always)
          - volume.seasonal_ranges + weekly_curve (when provided)
          - workers, tasks, business_rules, peak_staffing (advanced mode)
        Anything the user did NOT provide stays from the template.
        """
        import yaml as _yaml

        arch_id = cfg.get("archetype")
        arch = next((a for a in _presets["archetypes"] if a["id"] == arch_id), None)
        if arch is None:
            raise ValueError(f"Unknown archetype: {arch_id!r}")

        template_path = repo_root / arch["base_template"]
        if not template_path.exists():
            raise FileNotFoundError(f"Base template not found: {template_path}")

        base = _yaml.safe_load(template_path.read_text(encoding="utf-8"))
        if not isinstance(base, dict):
            raise ValueError(f"Base template is not a mapping: {template_path}")

        # Override facility name
        facility_name = (cfg.get("facility_name") or "").strip() or "Untitled Facility"
        base.setdefault("facility", {})["name"] = facility_name

        # Merge user-tuned reward weights on top of whatever the template
        # had (rewards: {} in current templates, but we don't assume that).
        weights = cfg.get("resulting_weights") or {}
        merged_rewards = dict(base.get("rewards") or {})
        merged_rewards.update(weights)
        base["rewards"] = merged_rewards

        # ── ADVANCED-MODE OVERLAYS ───────────────────────────────────
        # Wizard quick mode sends these fields as null/empty; advanced
        # mode populates them only for what the user actually edited.
        # Falling through to the template for unedited fields is the
        # whole point — users don't have to touch every knob.

        # Workers: replace the template roster wholesale when provided.
        workers_in = cfg.get("workers")
        if isinstance(workers_in, list) and workers_in:
            new_workers = []
            for i, w in enumerate(workers_in):
                if not isinstance(w, dict) or not w.get("name"):
                    continue
                wd = {
                    "id": i,
                    "name": str(w["name"]).strip(),
                    "base_oph": float(w.get("base_oph", 15)),
                    "shift_hours": float(w.get("shift_hours", 8)),
                    "shift_start": float(w.get("shift_start", 9)),
                    "role": str(w.get("role", "warehouse")),
                    "task_eligibility": w.get("task_eligibility", "all"),
                }
                new_workers.append(wd)
            if new_workers:
                base["workers"] = new_workers

        # Tasks: replace enabled + custom when either is provided.
        # QUICK MODE: force a minimal-viable task set regardless of what
        # the template carries. Live observation on test_v3: an 8-worker
        # facility with all 12 standard tasks enabled spent 47/64
        # worker-hours/day on secondary tasks (loading/receiving/
        # returns/QC/training/side_project) and only 1 hour on
        # management — capping grade at C even when 100% of orders
        # shipped, because management duty was starved. Quick-start
        # users overwhelmingly want core ops only; add the rest in
        # Advanced if you actually run them every day.
        QUICK_MODE_TASKS = ["pick", "pack", "restock", "management", "idle"]
        if cfg.get("mode") == "quick":
            base["tasks"] = {"enabled": list(QUICK_MODE_TASKS), "custom": []}
            # Strip worker task_eligibility entries that reference tasks
            # we just disabled (e.g. the example_small template workers
            # list "side_project" in their eligibility — without this
            # cleanup the schema validator emits a soft warning).
            allowed = set(QUICK_MODE_TASKS)
            for w in base.get("workers", []):
                te = w.get("task_eligibility")
                if isinstance(te, list):
                    w["task_eligibility"] = [t for t in te if t in allowed] or "all"
        else:
            tasks_in = cfg.get("tasks")
            if isinstance(tasks_in, dict):
                t_out = dict(base.get("tasks") or {})
                if isinstance(tasks_in.get("enabled"), list) and tasks_in["enabled"]:
                    t_out["enabled"] = list(tasks_in["enabled"])
                if isinstance(tasks_in.get("custom"), list):
                    custom_clean = []
                    for ct in tasks_in["custom"]:
                        if not isinstance(ct, dict) or not ct.get("task_id"):
                            continue
                        custom_clean.append({
                            "id": str(ct["task_id"]).strip(),
                            "display_name": str(ct.get("display_name", ct["task_id"])).strip(),
                            "output_type": str(ct.get("output_type", "hours")),
                            "hustle_eligible": bool(ct.get("hustle_eligible", False)),
                            "eligible_roles": list(ct.get("eligible_roles") or ["warehouse"]),
                            "reward_weight": float(ct.get("reward_weight", 1.0)),
                        })
                    if custom_clean:
                        t_out["custom"] = custom_clean
                # Per-task daily-hours caps + unmet penalties. Keep only
                # entries with a positive target; carry the matching
                # penalty (default "none").
                dh_in = tasks_in.get("daily_hours")
                if isinstance(dh_in, dict) and dh_in:
                    up_in = tasks_in.get("unmet_penalty") or {}
                    daily_hours, unmet_penalty = {}, {}
                    for t_id, hrs in dh_in.items():
                        try:
                            hv = float(hrs)
                        except (TypeError, ValueError):
                            continue
                        if hv <= 0:
                            continue
                        daily_hours[str(t_id)] = hv
                        unmet_penalty[str(t_id)] = str(up_in.get(t_id, "none"))
                    if daily_hours:
                        t_out["daily_hours"] = daily_hours
                        t_out["unmet_penalty"] = unmet_penalty
                base["tasks"] = t_out

        # Business rule overrides — only the keys the user actually set
        # on the equipment + shift-schedule + Saturday step. Everything
        # else stays from the template.
        rules_in = cfg.get("rules_overrides")
        if isinstance(rules_in, dict) and rules_in:
            br = dict(base.get("business_rules") or {})
            for k, v in rules_in.items():
                if v is None:
                    continue
                br[k] = v
            base["business_rules"] = br

        # Break schedule overrides — both modes have the dedicated step
        # 6.5 ("Confirm your break schedule"). Quick mode previously
        # inherited the template's breaks silently, so users were
        # surprised when the chat reported "morning break at 10:00,
        # lunch at 12:00" for facilities they thought they'd never
        # configured for breaks. Now if the user visits the breaks step
        # we honor their values; lunch goes into business_rules,
        # morning + afternoon become entries in the top-level `breaks`
        # list (with 0-duration entries dropped so "no break" is a
        # supported choice).
        breaks_in = cfg.get("breaks_override")
        if isinstance(breaks_in, dict):
            br = dict(base.get("business_rules") or {})
            if breaks_in.get("lunch_hour") is not None:
                br["lunch_hour"] = float(breaks_in["lunch_hour"])
            if breaks_in.get("lunch_duration") is not None:
                br["lunch_duration"] = float(breaks_in["lunch_duration"])
            base["business_rules"] = br

            new_breaks = []
            for prefix in ("morning", "afternoon"):
                h = breaks_in.get(f"{prefix}_break_hour")
                d = breaks_in.get(f"{prefix}_break_duration")
                if h is None or d is None or float(d) <= 0:
                    continue   # user opted out of this break
                new_breaks.append({
                    "hour": float(h),
                    "duration": float(d),
                    "staggered": False,
                })
            base["breaks"] = new_breaks

        # Peak-season staffing: only when the user provided extras > 0.
        peak_in = cfg.get("peak_staffing")
        if isinstance(peak_in, dict) and int(peak_in.get("extra_workers", 0)) > 0 \
                and isinstance(peak_in.get("months"), list) \
                and peak_in["months"]:
            base["peak_staffing"] = {
                "months": list(peak_in["months"]),
                "extra_workers": int(peak_in["extra_workers"]),
                "temp_oph_range": list(peak_in.get("temp_oph_range") or [8.0, 15.0]),
            }

        # Volume profile translation. The wizard collects per-intensity
        # actual ranges (e.g. slow=[60,100], normal=[200,300], peak=[300,440])
        # because real warehouses have asymmetric variance that doesn't fit
        # a single avg × multiplier formula. We map each month's intensity
        # bucket to its corresponding range. If the wizard didn't collect a
        # volume profile (older session, incomplete walkthrough), the
        # template's volume stays intact.
        vol = cfg.get("volume_profile") or {}
        season_ranges = vol.get("season_ranges") or {}

        def _bucket_range(bucket: str) -> tuple[int, int] | None:
            r = season_ranges.get(bucket) or {}
            lo, hi = r.get("low"), r.get("high")
            if not isinstance(lo, (int, float)) or not isinstance(hi, (int, float)):
                return None
            if lo <= 0 or hi <= 0 or hi < lo:
                return None
            return (int(round(float(lo))), int(round(float(hi))))

        normal_range = _bucket_range("normal")
        if normal_range is not None:
            slow_range = _bucket_range("slow") or normal_range
            peak_range = _bucket_range("peak") or normal_range
            band_map = {"slow": slow_range, "normal": normal_range, "peak": peak_range}
            month_intensity = vol.get("month_intensity") or {}
            seasonal = {}
            for m in ["january", "february", "march", "april", "may", "june",
                      "july", "august", "september", "october", "november", "december"]:
                bucket = month_intensity.get(m, "normal")
                lo, hi = band_map.get(bucket, normal_range)
                seasonal[m] = [lo, hi]
            base.setdefault("volume", {})["seasonal_ranges"] = seasonal

            # Weekly curve. The schema stores per-day low/high fractions of
            # the seasonal baseline. Build a peaked-or-flat curve depending
            # on the user's busiest_weekday choice. "none" → flat across the
            # week; otherwise the chosen day gets the maximum range and
            # adjacent days taper off — mirrors a real Mon-heavy or Fri-heavy
            # warehouse pattern.
            weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday"]
            busiest = (vol.get("busiest_weekday") or "none").lower()
            if busiest == "none" or busiest not in weekdays:
                # Flat — same fraction every weekday
                weekly = {d: [0.50, 1.00] for d in weekdays}
            else:
                # Peaked: busiest day = [0.80, 1.00], decreasing by ~0.15
                # per day of distance, floored at [0.10, 0.30].
                idx = weekdays.index(busiest)
                weekly = {}
                for j, d in enumerate(weekdays):
                    dist = abs(j - idx)
                    lo = max(0.10, 0.80 - 0.15 * dist)
                    hi = max(0.30, 1.00 - 0.15 * dist)
                    weekly[d] = [round(lo, 2), round(hi, 2)]
            base.setdefault("volume", {})["weekly_curve"] = weekly

        # Write to disk
        stem = _safe_filename(facility_name)
        out_path = user_configs_dir / f"{stem}.yaml"
        # If a config already exists for this facility name, version it
        # rather than silently overwriting (warehouses iterate).
        if out_path.exists():
            i = 2
            while (user_configs_dir / f"{stem}_v{i}.yaml").exists():
                i += 1
            out_path = user_configs_dir / f"{stem}_v{i}.yaml"

        yaml_text = _yaml.safe_dump(base, sort_keys=False, default_flow_style=False)
        out_path.write_text(yaml_text, encoding="utf-8")

        return {
            "facility_name": facility_name,
            "yaml_path": str(out_path),
            "yaml_text": yaml_text,
        }

    def _start_training(yaml_path: str, episodes: int = 50) -> dict:
        """Spawn cmd_finetune as a detached subprocess. Returns a job_id
        that future /train/{id}/status calls can use.

        Uses the existing CLI entry point so we get all the same defaults
        + validation as a manual `clark finetune` run. The subprocess's
        stdout/stderr stream to a per-job log file so a wizard progress
        view can tail it later.

        Default episodes lowered 500 → 50 to match the Jack-validation
        floor (50 eps already cuts F-rate 60% and lifts A+B share
        57.5%→83.5% per the README's Validated-on-Jack table). At
        ~4 min/ep on a consumer GPU, that's ~3.5h end-to-end vs the
        old default's ~36h. Users wanting deeper training pass a
        higher value from the wizard's review step.
        """
        import subprocess as _sp
        import uuid as _uuid

        if not Path(yaml_path).exists():
            raise FileNotFoundError(f"Config YAML missing: {yaml_path}")

        job_id = str(_uuid.uuid4())
        job_log_dir = user_logs_dir / job_id
        job_log_dir.mkdir(parents=True, exist_ok=True)
        stem = Path(yaml_path).stem
        ckpt_path = user_checkpoints_dir / f"{stem}.pt"
        base_model = repo_root / "clark" / "data" / "checkpoints" / "clark_foundation.pt"

        if not base_model.exists():
            raise FileNotFoundError(
                f"Foundation checkpoint not found at {base_model}. "
                "Run `clark pretrain` first or download a foundation model."
            )

        stdout_log = open(job_log_dir / "stdout.log", "wb")
        # NOTE: cmd_finetune doesn't currently expose --log-dir, so finetune
        # defaults the log dir to a sibling of --output. The job_log_dir we
        # create above just holds the subprocess stdout for the wizard's
        # progress view; the real episode logs live next to the checkpoint.
        # `-u` (unbuffered) is critical: without it, Python's stdout is
        # block-buffered when redirected to a file, so the wizard's log
        # tail only sees output after the subprocess exits. With
        # crashes, the user gets either a stale empty file or a
        # post-mortem dump — never the in-progress lines that would
        # let them tell if training is actually progressing.
        cmd = [
            sys.executable, "-u", "-m", "cli.main", "finetune",
            "--config", str(yaml_path),
            "--base", str(base_model),
            "--output", str(ckpt_path),
            "--episodes", str(int(episodes)),
            # Write episode logs + training_metrics.json into the job dir so
            # the wizard's progress poll reads from one known location
            # (instead of guessing logs_<facility-name> next to the output).
            "--log-dir", str(job_log_dir),
        ]
        # stdin=DEVNULL is critical on Windows: the wizard subprocess
        # (this process) was launched from a bat → cmd → python chain
        # whose stdin handle may not be a proper console. Without an
        # explicit DEVNULL here, the trainer subprocess inherits that
        # broken handle and Python's sys.stdin init fails immediately
        # with:
        #   Fatal Python error: init_sys_streams: can't initialize sys
        #   standard streams
        #   KeyboardInterrupt during <frozen codecs>:186
        # The training subprocess then exits in <1s, writes only that
        # 216-byte traceback to stdout.log, and never produces a
        # checkpoint. The wizard reports "training started" because
        # Popen succeeded, but the policy never trains.
        #
        # DETACHMENT (the reason early runs died ~0.3s after launch with
        # "Fine-tuning interrupted"): without these flags the child shares
        # the wizard's console + process group, so a Ctrl-C / Ctrl-Break /
        # console-close that hits the wizard is delivered by Windows to the
        # child too — instant KeyboardInterrupt before the model even loads.
        # That also made the UI's "training continues even if you close this
        # window" promise false. Detaching gives the trainer its own process
        # group and no inherited console, so wizard signals can't reach it.
        detach_kwargs = {}
        if os.name == "nt":
            # DETACHED_PROCESS (0x08): no inherited console.
            # CREATE_NEW_PROCESS_GROUP (0x200): own group, immune to the
            # wizard's Ctrl-C/Ctrl-Break. stdout/stderr already go to a file
            # and stdin is DEVNULL, so the child needs no console of its own.
            detach_kwargs["creationflags"] = 0x00000008 | 0x00000200
        else:
            # POSIX: detach from the controlling terminal / session so a
            # SIGHUP/SIGINT to the wizard doesn't propagate.
            detach_kwargs["start_new_session"] = True
        proc = _sp.Popen(cmd, cwd=str(repo_root),
                         stdin=_sp.DEVNULL,
                         stdout=stdout_log, stderr=_sp.STDOUT,
                         **detach_kwargs)
        training_jobs[job_id] = {
            "pid": proc.pid,
            "config_path": yaml_path,
            "log_dir": str(job_log_dir),
            "checkpoint_path": str(ckpt_path),
            "episodes": int(episodes),
            "started_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        }
        training_procs[job_id] = proc
        return {"job_id": job_id, **training_jobs[job_id]}

    def _list_sessions() -> list[dict]:
        out = []
        for p in sorted(sessions_dir.glob("*.json")):
            try:
                data = _json.loads(p.read_text(encoding="utf-8"))
                out.append({
                    "session_id": data.get("session_id", p.stem),
                    "facility_name": data.get("facility_name", "(unnamed)"),
                    "updated_at": data.get("updated_at", ""),
                })
            except Exception:
                continue
        # Most recently updated first
        out.sort(key=lambda s: s.get("updated_at", ""), reverse=True)
        return out

    class WizardHandler(http.server.BaseHTTPRequestHandler):
        def log_message(self, fmt, *a):
            pass  # suppress default access log spam

        def do_GET(self):
            path = urlparse(self.path).path
            if path in ("/", "/index.html"):
                # Re-read each request so editing the HTML during dev
                # takes effect on browser refresh without a server restart.
                self._send(200, "text/html; charset=utf-8", index_html.read_bytes())
            elif path == "/presets":
                self._send(200, "application/json", presets_path.read_bytes())
            elif path == "/sessions":
                payload = {"sessions": _list_sessions()}
                self._send(200, "application/json",
                           _json.dumps(payload).encode("utf-8"))
            elif path.startswith("/sessions/"):
                sid = path[len("/sessions/"):]
                fpath = sessions_dir / f"{sid}.json"
                if not fpath.exists():
                    self._send(404, "application/json",
                               b'{"error":"session not found"}')
                    return
                self._send(200, "application/json", fpath.read_bytes())
            elif path.startswith("/train/") and path.endswith("/status"):
                # GET /train/{job_id}/status — poll subprocess liveness.
                job_id = path[len("/train/"):-len("/status")]
                job = training_jobs.get(job_id)
                if job is None:
                    self._send(404, "application/json",
                               b'{"error":"unknown job id"}')
                    return
                # Liveness check. MUST NOT use os.kill(pid, 0) on Windows:
                # signal 0 is CTRL_C_EVENT there, so it would send a Ctrl-C
                # to the trainer's process group (which previously killed
                # freshly-started runs on the first poll). _job_alive uses
                # the Popen handle (proc.poll()) instead.
                alive = _job_alive(job_id, job["pid"])
                payload = {**job, "alive": alive}

                # Progress: read the trainer's training_metrics.json from the
                # job log dir (we point finetune --log-dir there). The trainer
                # writes status.current_episode / n_episodes_target / elapsed_s
                # on its heartbeat; before the first write we fall back to the
                # requested episode count so the bar still has a target.
                cur = 0
                target = job.get("episodes")
                elapsed = 0.0
                try:
                    mp = Path(job["log_dir"]) / "training_metrics.json"
                    if mp.exists():
                        data = _json.loads(mp.read_text(encoding="utf-8"))
                        st = data.get("status") or {}
                        cur = int(st.get("current_episode", 0))
                        target = int(st.get("n_episodes_target", 0)) or target
                        elapsed = float(st.get("elapsed_s", 0.0))
                except Exception:
                    pass
                eta_s = None
                if alive and cur > 0 and target and elapsed > 0:
                    eta_s = max(0, int((elapsed / cur) * (target - cur)))
                payload["current_episode"] = cur
                payload["n_episodes_target"] = target
                payload["elapsed_s"] = elapsed
                payload["eta_s"] = eta_s
                # done = the subprocess has exited (cleanly or not). The
                # client decides "complete" vs "stopped early" from cur/target.
                payload["done"] = not alive
                self._send(200, "application/json",
                           _json.dumps(payload).encode("utf-8"))
            else:
                self._send(404, "text/plain", b"Not found")

        def do_POST(self):
            path = urlparse(self.path).path
            length = int(self.headers.get("Content-Length", 0))
            raw = self.rfile.read(length) if length else b"{}"
            try:
                body = _json.loads(raw)
            except Exception:
                self._send(400, "application/json", b'{"error":"invalid JSON"}')
                return

            # Defense in depth: reject cross-origin POSTs. Browsers
            # CAN reach localhost from any page; the wizard does
            # state-changing things (save session, kick off training
            # subprocess) that should never be triggered by random
            # tabs the user has open.
            import re as _re
            origin = self.headers.get("Origin", "")
            if origin and origin not in (
                    f"http://localhost:{port}",
                    f"http://127.0.0.1:{port}"):
                self._send(403, "application/json",
                           b'{"error":"cross-origin POSTs not allowed"}')
                return

            if path == "/sessions":
                sid = body.get("session_id") or str(uuid.uuid4())
                # Sanitize: only safe filename chars. Blocks ../
                # traversal, absolute paths, NULs, etc.
                if not _re.fullmatch(r"[A-Za-z0-9_-]{1,64}", sid):
                    self._send(400, "application/json",
                               b'{"error":"invalid session_id"}')
                    return
                now = datetime.now(timezone.utc).isoformat(timespec="seconds")
                fpath = sessions_dir / f"{sid}.json"
                created_at = now
                if fpath.exists():
                    try:
                        existing = _json.loads(fpath.read_text(encoding="utf-8"))
                        created_at = existing.get("created_at", now)
                    except Exception:
                        pass
                doc = {
                    "session_id": sid,
                    "facility_name": body.get("facility_name", ""),
                    "selected_archetype": body.get("selected_archetype"),
                    "season_ranges": body.get("season_ranges", {}),
                    "month_intensity": body.get("month_intensity", {}),
                    "busiest_weekday": body.get("busiest_weekday"),
                    "answers": body.get("answers", {}),
                    "current_step": body.get("current_step", 0),
                    "created_at": created_at,
                    "updated_at": now,
                }
                fpath.write_text(_json.dumps(doc, indent=2), encoding="utf-8")
                self._send(200, "application/json",
                           _json.dumps({"session_id": sid, "saved_at": now}).encode("utf-8"))

            elif path == "/validate":
                result = _validate_config(body)
                self._send(200, "application/json",
                           _json.dumps(result).encode("utf-8"))

            elif path == "/generate":
                # Materialize the YAML from archetype + answers.
                # Returns yaml_text (for preview) and yaml_path (on disk).
                try:
                    result = _generate_yaml(body)
                    self._send(200, "application/json",
                               _json.dumps(result).encode("utf-8"))
                except Exception as e:
                    self._send(400, "application/json",
                               _json.dumps({"error": str(e)}).encode("utf-8"))

            elif path == "/train/start":
                # Body: {"yaml_path": "...", "episodes": 50}
                # `episodes` defaults to 50 (Jack-validated floor) and is
                # clamped to [10, 5000] server-side. The wizard's review
                # step exposes it; users can crank up for deeper training.
                yaml_path = body.get("yaml_path")
                if not yaml_path:
                    self._send(400, "application/json",
                               b'{"error":"yaml_path required"}')
                    return
                try:
                    episodes = int(body.get("episodes", 50))
                except (TypeError, ValueError):
                    episodes = 50
                episodes = max(10, min(5000, episodes))
                # Path confinement: the wizard writes configs under
                # user_configs_dir; refuse to spawn a training run
                # against an arbitrary YAML elsewhere on disk.
                try:
                    yp = Path(yaml_path).resolve()
                    allowed = user_configs_dir.resolve()
                    yp.relative_to(allowed)
                except (ValueError, OSError):
                    self._send(400, "application/json",
                               b'{"error":"yaml_path must be under '
                               b'user_configs_dir"}')
                    return
                try:
                    result = _start_training(str(yp), episodes=episodes)
                    self._send(200, "application/json",
                               _json.dumps(result).encode("utf-8"))
                except Exception as e:
                    self._send(400, "application/json",
                               _json.dumps({"error": str(e)}).encode("utf-8"))

            else:
                self._send(404, "text/plain", b"Not found")

        def _send(self, code: int, ctype: str, body: bytes):
            self.send_response(code)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            # No wildcard CORS — these servers are localhost-only and
            # same-origin in normal use. Wildcard '*' would let any
            # web page in the user's browser read responses.
            self.end_headers()
            self.wfile.write(body)

    # ThreadingHTTPServer (not HTTPServer): single-threaded would queue
    # every browser fetch behind any slow handler — including the
    # synchronous subprocess.Popen in /train/start. When training
    # kicked off, concurrent /validate or /generate calls from the
    # same tab failed with "TypeError: Failed to fetch" because they
    # were waiting on the busy thread. Threading lets each request
    # finish independently.
    server = http.server.ThreadingHTTPServer(("localhost", port), WizardHandler)
    url = f"http://localhost:{port}"
    print(f"  Wizard:       {url}")
    print(f"  Sessions dir: {sessions_dir}")
    print(f"  Press Ctrl+C to stop.\n")

    if os.environ.get("CLARK_NO_BROWSER") != "1":
        def _open():
            import time as _time
            _time.sleep(0.5)
            webbrowser.open(url)
        threading.Thread(target=_open, daemon=True).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nWizard stopped.")


# ── Entry point ───────────────────────────────────────────────────────────────

def cmd_eval(args: argparse.Namespace):
    """Held-out evaluation: full-year sims on freshly-sampled synthetic
    facilities, production grader, metric distributions per stage."""
    _header()
    model_path = Path(args.model)
    if not model_path.exists():
        _die(f"Checkpoint not found: {model_path}")
    try:
        stages = tuple(int(s) for s in str(args.stages).split(",") if s.strip())
    except ValueError:
        _die(f"--stages must be comma-separated ints, got {args.stages!r}")

    from clark.inference.evaluate import evaluate
    subject = f"baseline '{args.baseline}'" if args.baseline else model_path.name
    print(f"Evaluating {subject} — {args.n_per_stage} held-out "
          f"facilities/stage (stages {','.join(map(str, stages))}), "
          f"full-year sims + production grader.")
    print("Every facility is freshly sampled (held-out), so this measures "
          "generalization. Baselines obey the same action masks as the policy.\n")

    year_runner = None
    if args.baseline in ("heuristic", "greedy"):
        from clark.inference.baseline import GreedyScheduler, run_one_year_baseline
        agent = GreedyScheduler()
        year_runner = run_one_year_baseline
    else:
        try:
            from clark.agent.ppo import ClarkAgent
            agent = ClarkAgent.load(str(model_path), device=args.device)
        except Exception as e:
            _die(f"Failed to load model: {e}")

    def _progress(stage, done, total):
        if sys.stdout.isatty():
            # interactive terminal: update one line in place
            end = "\n" if done == total else ""
            print(f"\r  stage {stage}: {done}/{total} years simulated…", end=end, flush=True)
        else:
            # redirected to a log (background run): one clean line per facility
            # so the file is tailable live
            print(f"  stage {stage}: {done}/{total} years simulated", flush=True)

    res = evaluate(agent, n_per_stage=args.n_per_stage, stages=stages,
                   base_seed=args.seed, progress=_progress, year_runner=year_runner)

    def _row(label, agg):
        a, ab, f = agg["a_pct"], agg["ab_pct"], agg["f_pct"]
        sw, cp = agg["ship_win_pct"], agg["completion_pct"]
        return ("  %-8s| %5.1f | %5.1f [%4.1f-%4.1f] | %5.1f | %6.1f | %6.1f"
                % (label, a["median"], ab["median"], ab["p10"], ab["p90"],
                   f["median"], sw["median"], cp["median"]))

    print("\n  Median per metric across held-out facilities; [p10-p90] = spread on A+B.")
    print("  Stage   |  A%  |  A+B% [p10-p90]  |  F%  | shipwin% |  cmp%")
    print("  " + "-" * 62)
    for st in stages:
        print(_row(f"stage {st}", res["per_stage"][st]))
    print("  " + "-" * 62)
    print(_row("overall", res["overall"]))

    if len(stages) > 1:
        lo, hi = stages[0], stages[-1]
        drop = (res["per_stage"][lo]["ab_pct"]["median"]
                - res["per_stage"][hi]["ab_pct"]["median"])
        print(f"\n  Generalization: A+B median moves {(-drop):+.1f} pts from stage "
              f"{lo} to stage {hi} (smaller drop = generalizes better to harder configs).")

    if args.json:
        import json as _json
        Path(args.json).write_text(_json.dumps(res, indent=2), encoding="utf-8")
        print(f"\n  Full results written to {args.json}")


def main():
    parser = build_parser()
    args = parser.parse_args()

    dispatch = {
        "init":      cmd_init,
        "validate":  cmd_validate,
        "pretrain":  cmd_pretrain,
        "finetune":  cmd_finetune,
        "plan":      cmd_plan,
        "dashboard": cmd_dashboard,
        "ops":       cmd_ops,
        "wizard":    cmd_wizard,
        "serve":     cmd_serve,
        "mcp":       cmd_mcp,
        "eval":      cmd_eval,
    }

    fn = dispatch.get(args.command)
    if fn is None:
        parser.print_help()
        sys.exit(1)

    fn(args)


# Allow direct invocation: python cli/main.py <command>
app = main  # pyproject.toml entry point: clark = "cli.main:app"

if __name__ == "__main__":
    main()
