"""
Clark CLI — Foundation Model for Warehouse Optimization
Entry point: `clark` (set via pyproject.toml: clark = "cli.main:app")

Note: typer is not installed. Using argparse as fallback.
Install typer with: pip install typer
"""
from __future__ import annotations

import argparse
import calendar
import os
import random
import sys
from datetime import date, timedelta
from pathlib import Path

# ── Rich (optional) ──────────────────────────────────────────────────────────

try:
    from rich.console import Console
    from rich.table import Table
    _RICH = True
    console = Console()
except ImportError:
    _RICH = False
    console = None

HEADER = "Clark — Foundation Model for Warehouse Optimization"
HEADER_LINE = "=" * len(HEADER)


def _header():
    if _RICH:
        console.print(f"\n[bold cyan]{HEADER}[/bold cyan]")
        console.print(f"[dim]{HEADER_LINE}[/dim]\n")
    else:
        print(f"\n{HEADER}")
        print(f"{HEADER_LINE}\n")


def _ok(msg: str):
    if _RICH:
        console.print(f"[bold green]{msg}[/bold green]")
    else:
        print(msg)


def _warn(msg: str):
    if _RICH:
        console.print(f"[bold yellow]  Warning: {msg}[/bold yellow]")
    else:
        print(f"  Warning: {msg}")


def _err(msg: str):
    if _RICH:
        console.print(f"[bold red]  Error: {msg}[/bold red]")
    else:
        print(f"  Error: {msg}", file=sys.stderr)


def _die(msg: str):
    _err(msg)
    sys.exit(1)


# ── Template content ──────────────────────────────────────────────────────────

def _load_template(template: str, name: str) -> str:
    """Return template YAML text with a header comment and the facility name substituted."""
    clark_root = Path(__file__).parent.parent
    template_map = {
        "small":    clark_root / "clark" / "data" / "configs" / "example_small.yaml",
        "large":    clark_root / "clark" / "data" / "configs" / "example_large.yaml",
        "full":     clark_root / "clark" / "data" / "configs" / "example_1.yaml",
    }
    path = template_map.get(template)
    if path is None or not path.exists():
        _die(f"Template '{template}' not found at {path}.")

    text = path.read_text(encoding="utf-8")

    # Swap facility name into the `facility:` block's name field. Scoped
    # rewrite so it can't accidentally hit a `name:` line inside the worker
    # roster that happens to match the template's facility name string.
    lines = text.splitlines(keepends=True)
    in_facility_block = False
    for i, line in enumerate(lines):
        if line.startswith("facility:"):
            in_facility_block = True
            continue
        if in_facility_block:
            # End of block when we hit a non-indented, non-blank line
            if line and not line[0].isspace() and line.strip():
                break
            stripped = line.strip()
            if stripped.startswith("name:"):
                indent = line[: len(line) - len(line.lstrip())]
                lines[i] = f'{indent}name: "{name}"\n'
                break
    text = "".join(lines)

    header_comment = "# Generated by 'clark init' — fill in your real values\n"
    return header_comment + text


# ── Commands ──────────────────────────────────────────────────────────────────

def cmd_init(args: argparse.Namespace):
    _header()
    output_path = Path(args.output_path)

    print("Scaffolding a new facility config...\n")

    # Prompt: facility name
    try:
        name = input("Facility name: ").strip()
        if not name:
            name = "My Warehouse"
    except (EOFError, KeyboardInterrupt):
        name = "My Warehouse"

    # Prompt: number of workers (informational)
    try:
        input("Approximate number of workers: ").strip()
    except (EOFError, KeyboardInterrupt, ValueError):
        pass

    # Prompt: template
    try:
        tmpl_input = input("Start from template? [small/large/full] (default: small): ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        tmpl_input = ""

    tmpl = tmpl_input if tmpl_input in ("small", "large", "full") else "small"

    content = _load_template(tmpl, name)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    _ok(f"Config written to: {output_path}")
    print(f"Template: {tmpl}")
    print("Edit the file to match your facility's real values, then run:")
    print(f"  clark validate {output_path}")


def cmd_validate(args: argparse.Namespace):
    _header()
    config_path = Path(args.config_path)

    if not config_path.exists():
        _die(f"Config file not found: {config_path}")

    try:
        from clark.config.schema import FacilityConfig
        config = FacilityConfig.from_yaml(config_path)
    except Exception as e:
        _die(f"Failed to load config: {e}")

    errors, warnings = config.validate()

    # Volume summary: find overall min/max across all months
    all_lows = [v[0] for v in config.volume.seasonal_ranges.values()]
    all_highs = [v[1] for v in config.volume.seasonal_ranges.values()]
    vol_lo = min(all_lows) if all_lows else 0
    vol_hi = max(all_highs) if all_highs else 0

    print(f"  Name:         {config.name}")
    print(f"  Workers:      {config.num_workers}")
    print(f"  Tasks:        {config.num_tasks}  ({', '.join(config.task_ids)})")
    print(f"  Volume range: {vol_lo}–{vol_hi} orders/day")
    print()

    if errors:
        for e in errors:
            _err(e)
        print()
    if warnings:
        for w in warnings:
            _warn(w)
        print()

    if errors:
        _err(f"Config has {len(errors)} blocking error(s). Fix before training.")
        sys.exit(1)
    else:
        _ok("Config is valid!")


def cmd_pretrain(args: argparse.Namespace):
    _header()
    print(f"Starting pre-training: {args.episodes} episodes")
    print(f"Output: {args.output}")
    print()

    # Auto log-interval: batched runs complete episodes in chunks of n_envs at
    # a time, so a lower number keeps the screen updating.
    log_interval = args.log_interval
    if log_interval == 0:
        log_interval = 4 if args.n_envs > 1 else 10

    try:
        if args.n_envs > 1:
            from clark.training.pretrain import pretrain_batched
            pretrain_batched(
                n_episodes=args.episodes,
                n_envs=args.n_envs,
                output_path=args.output,
                save_interval=args.save_interval,
                log_interval=log_interval,
                device=args.device,
                use_amp=not args.no_amp,
                compile_model=args.compile,
                use_mp=args.mp,
                years_per_config=args.years_per_config,
            )
        else:
            from clark.training.pretrain import pretrain
            pretrain(
                n_episodes=args.episodes,
                output_path=args.output,
                save_interval=args.save_interval,
                log_interval=log_interval,
                device=args.device,
                use_amp=not args.no_amp,
                compile_model=args.compile,
                years_per_config=args.years_per_config,
            )
    except KeyboardInterrupt:
        print("\nPre-training interrupted.")
        sys.exit(1)
    except Exception as e:
        _die(f"Pre-training failed: {e}")


def cmd_finetune(args: argparse.Namespace):
    _header()

    config_path = Path(args.config)
    base_path = Path(args.base)

    if not config_path.exists():
        _die(f"Config not found: {config_path}")
    if not base_path.exists():
        _die(f"Base checkpoint not found: {base_path}")

    print(f"Fine-tuning on config: {config_path}")
    print(f"Base model:            {base_path}")
    print(f"Output:                {args.output}")
    print(f"Episodes: {args.episodes}  LR: {args.lr}  freeze-encoder: {args.freeze_encoder}")
    print()

    try:
        from clark.training.finetune import finetune
        finetune(
            config_path=str(config_path),
            base_model_path=str(base_path),
            output_path=args.output,
            n_episodes=args.episodes,
            lr=args.lr,
            freeze_encoder=args.freeze_encoder,
        )
    except KeyboardInterrupt:
        print("\nFine-tuning interrupted.")
        sys.exit(1)
    except Exception as e:
        _die(f"Fine-tuning failed: {e}")


def _sample_volume_for_date(config, target_date: date) -> tuple[int, str]:
    """
    Sample a realistic order volume for a specific date using the config's
    seasonal_ranges and weekly_curve.

    Returns (volume, label) where label is "Normal Day", "High Volume Day", etc.
    """
    month_name = calendar.month_name[target_date.month]
    dow = target_date.weekday()  # 0=Monday, 4=Friday

    dow_name_map = {
        0: "monday", 1: "tuesday", 2: "wednesday",
        3: "thursday", 4: "friday",
    }

    # Get seasonal base range
    ranges = config.volume.seasonal_ranges
    vol_range = None
    if month_name in ranges:
        vol_range = tuple(ranges[month_name])
    else:
        for k, v in ranges.items():
            if k.lower() == month_name.lower():
                vol_range = tuple(v)
                break
    if vol_range is None:
        vol_range = (100, 300)

    vol_lo, vol_hi = vol_range
    vol_spread = vol_hi - vol_lo

    # Apply weekly curve
    curve = config.volume.weekly_curve
    dow_name = dow_name_map.get(dow, "monday")
    if dow_name in curve:
        pct_lo, pct_hi = curve[dow_name]
    else:
        pct_lo, pct_hi = 0.5, 1.0

    day_vol_lo = vol_lo + int(vol_spread * pct_lo)
    day_vol_hi = vol_lo + int(vol_spread * pct_hi)
    volume = random.randint(day_vol_lo, max(day_vol_lo, day_vol_hi))

    # Label
    high_threshold = config.rules.high_volume_day_orders
    if volume >= high_threshold:
        label = "High Volume Day"
    elif volume >= high_threshold * 0.6:
        label = "Moderate Volume Day"
    else:
        label = "Normal Day"

    return volume, label


def _run_one_plan_day(config, agent, target_date: date, volume: int) -> list[tuple]:
    """
    Simulate the opening assignment for a single day by running the first agent
    step. Returns list of (worker_name, task_name, hustle).
    """
    from clark.env.year_env import YearEnv
    from clark.agent.state import StateBuilder
    from clark.agent.actions import get_action_mask, get_hustle_mask

    env = YearEnv(config)
    builder = StateBuilder(config)

    dow = target_date.weekday()
    month = target_date.month

    env.reset()
    # Re-initialize the inner day_env for this specific date/volume
    env.day_env.reset(
        force_month=month,
        force_dow=dow,
        force_volume=volume,
    )

    agent.reset_hidden()

    state_dict = builder.build(env.day_env)
    mask = get_action_mask(env.day_env)
    hmask = get_hustle_mask(env.day_env)
    # select_action_from_dict returns 5: task/hustle actions, task_lp,
    # hustle_lp, value. Previously unpacked 4 -> `clark plan` crashed with
    # "too many values to unpack (expected 4)" the moment a checkpoint
    # existed. The test suite missed it (no end-to-end plan-path test);
    # test_plan_path.py now pins the 5-tuple contract.
    task_actions, hustle_actions, _task_lp, _hustle_lp, _value = (
        agent.select_action_from_dict(state_dict, mask, hustle_mask=hmask)
    )

    assignments = []
    for i, worker in enumerate(config.workers):
        task_idx = task_actions[i]
        task_name = config.task_ids[task_idx] if task_idx < len(config.task_ids) else "unknown"
        hustle = bool(hustle_actions[i])
        assignments.append((worker.name, task_name, hustle))

    return assignments


def cmd_plan(args: argparse.Namespace):
    _header()

    config_path = Path(args.config)
    model_path = Path(args.model)

    if not config_path.exists():
        _die(f"Config not found: {config_path}")
    if not model_path.exists():
        _die(f"Model checkpoint not found: {model_path}")

    # Parse date
    try:
        if args.date:
            start_date = date.fromisoformat(args.date)
        else:
            start_date = date.today()
    except ValueError:
        _die(f"Invalid date format: {args.date!r}. Use YYYY-MM-DD.")

    try:
        from clark.config.schema import FacilityConfig
        config = FacilityConfig.from_yaml(config_path)
    except Exception as e:
        _die(f"Failed to load config: {e}")

    try:
        from clark.agent.ppo import ClarkAgent
        agent = ClarkAgent.load(str(model_path))
    except Exception as e:
        _die(f"Failed to load model: {e}")

    days_ahead = max(1, args.days)

    for day_offset in range(days_ahead):
        target_date = start_date + timedelta(days=day_offset)

        # Skip weekends
        if target_date.weekday() >= 5:
            continue

        volume, vol_label = _sample_volume_for_date(config, target_date)
        day_name = calendar.day_name[target_date.weekday()]
        date_str = target_date.strftime("%Y-%m-%d")

        try:
            assignments = _run_one_plan_day(config, agent, target_date, volume)
        except Exception as e:
            _die(f"Failed to generate plan for {date_str}: {e}")

        if _RICH:
            title = f"Shift Plan: {day_name} {date_str}"
            border_len = max(len(title) + 4, 46)
            top_border = "╔" + "═" * (border_len - 2) + "╗"
            bot_border = "╚" + "═" * (border_len - 2) + "╝"

            console.print(f"\n[bold cyan]{top_border}[/bold cyan]")
            console.print(f"[bold cyan]║[/bold cyan] [bold]{title}[/bold]")
            console.print(f"[bold cyan]║[/bold cyan] Forecast: ~{volume} orders ([italic]{vol_label}[/italic])")
            console.print(f"[bold cyan]║[/bold cyan]")

            table = Table(show_header=True, header_style="bold", box=None,
                          padding=(0, 1), show_edge=False)
            table.add_column("Worker", min_width=14)
            table.add_column("Task", min_width=16)
            table.add_column("Hustle", min_width=6)

            for worker_name, task_name, hustle in assignments:
                hustle_str = "[green]Yes[/green]" if hustle else "No"
                table.add_row(worker_name, task_name.replace("_", " ").title(), hustle_str)

            console.print(table)
            console.print(f"[bold cyan]{bot_border}[/bold cyan]")
        else:
            title = f"Shift Plan: {day_name} {date_str}"
            border_len = max(len(title) + 4, 46)
            top_border = "╔" + "═" * (border_len - 2) + "╗"
            bot_border = "╚" + "═" * (border_len - 2) + "╝"

            print(f"\n{top_border}")
            print(f"║ {title}")
            print(f"║ Forecast: ~{volume} orders ({vol_label})")
            print(f"║")
            print(f"║ {'Worker':<14} | {'Task':<16} | Hustle")
            print(f"║ {'-'*14}-+-{'-'*16}-+-------")
            for worker_name, task_name, hustle in assignments:
                task_display = task_name.replace("_", " ").title()
                hustle_str = "Yes" if hustle else "No"
                print(f"║ {worker_name:<14} | {task_display:<16} | {hustle_str}")
            print(f"{bot_border}")


def cmd_dashboard(args: argparse.Namespace):
    _header()

    log_dir = Path(args.log_dir).resolve()
    port = args.port
    dashboard_html = Path(__file__).parent.parent / "clark" / "dashboard" / "dashboard.html"

    if not dashboard_html.exists():
        _die(f"Dashboard HTML not found at {dashboard_html}")

    if not log_dir.exists():
        _warn(f"Log directory does not exist yet: {log_dir}")
        _warn("Dashboard will show no data until training produces logs.")

    import http.server
    import threading
    import webbrowser

    class DashboardHandler(http.server.BaseHTTPRequestHandler):
        def log_message(self, fmt, *a):
            pass  # suppress default access log spam

        def do_GET(self):
            from urllib.parse import urlparse
            path = urlparse(self.path).path

            if path in ("/", "/index.html"):
                # Re-read on every request so editing the HTML during a run
                # takes effect on next browser refresh — no need to restart
                # the server. Cheap (~2KB file, OS page-cached).
                self._send(200, "text/html; charset=utf-8", dashboard_html.read_bytes())
            elif path in ("/data/year_snapshot.json", "/clark/data/year_snapshot.json"):
                self._serve_json("year_snapshot.json")
            elif path == "/data/episode_log.json":
                self._serve_json("episode_log.json")
            elif path == "/data/training_metrics.json":
                self._serve_json("training_metrics.json")
            elif path == "/status":
                # Tiny lightweight endpoint — dashboard uses this for the
                # live-pill liveness check without paying the cost of a
                # full training_metrics.json fetch.
                self._serve_status()
            else:
                self._send(404, "text/plain", b"Not found")

        def _serve_status(self):
            import json as _json
            fpath = log_dir / "training_metrics.json"
            payload = {"alive": False, "current_episode": 0}
            if fpath.exists():
                try:
                    data = _json.loads(fpath.read_text())
                    payload = data.get("status", payload)
                except Exception:
                    pass
            self._send(200, "application/json",
                       _json.dumps(payload).encode("utf-8"))

        def _serve_json(self, filename: str):
            fpath = log_dir / filename
            if fpath.exists():
                try:
                    data = fpath.read_bytes()
                    self._send(200, "application/json", data)
                except Exception:
                    self._send(500, "text/plain", b"Error reading file")
            else:
                # Return empty valid structure so dashboard doesn't error out
                self._send(200, "application/json",
                           b'{"episodes":[],"training_stats":{},"year_summary":{}}')

        def _send(self, code: int, ctype: str, body: bytes):
            self.send_response(code)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(body)

    server = http.server.HTTPServer(("localhost", port), DashboardHandler)

    url = f"http://localhost:{port}"
    print(f"  Dashboard: {url}")
    print(f"  Log dir:   {log_dir}")
    print(f"  Auto-refreshes every 10s while training is running.")
    print(f"  Press Ctrl+C to stop.\n")

    # Open browser after a short delay
    def _open():
        import time
        time.sleep(0.5)
        webbrowser.open(url)
    threading.Thread(target=_open, daemon=True).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nDashboard stopped.")


# ── Argument parser ───────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="clark",
        description=HEADER,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")
    sub.required = True

    # init
    p_init = sub.add_parser("init", help="Scaffold a new facility config YAML.")
    p_init.add_argument("output_path", metavar="OUTPUT_PATH",
                        help="Path to write the new YAML config.")

    # validate
    p_val = sub.add_parser("validate", help="Load and validate a facility config.")
    p_val.add_argument("config_path", metavar="CONFIG_PATH",
                       help="Path to the facility YAML config.")

    # pretrain
    p_pre = sub.add_parser("pretrain", help="Pre-train the Clark foundation model.")
    p_pre.add_argument("--episodes", type=int, default=10000,
                       help="Number of training episodes (default: 10000).")
    p_pre.add_argument("--output", type=str,
                       default="clark/data/checkpoints/clark_foundation.pt",
                       help="Output checkpoint path.")
    p_pre.add_argument("--log-interval", type=int, default=0,
                       help="Print progress every N episodes "
                            "(0 = auto: 4 batched, 10 single-env).")
    p_pre.add_argument("--save-interval", type=int, default=100,
                       help="Save checkpoint every N episodes (default: 100).")
    p_pre.add_argument("--device", type=str, default="cpu",
                       help="torch device: 'cpu', 'cuda', 'cuda:0', etc. "
                            "(default: cpu).")
    p_pre.add_argument("--n-envs", type=int, default=1,
                       help="Parallel envs for batched pretrain. 1 = single-env, "
                            ">1 = batched (default: 1).")
    p_pre.add_argument("--no-amp", action="store_true",
                       help="Disable bf16 autocast on CUDA (default: enabled).")
    p_pre.add_argument("--compile", action="store_true",
                       help="torch.compile the model (~30s warmup, then faster). "
                            "Requires Triton; not supported on Windows.")
    p_pre.add_argument("--mp", action="store_true",
                       help="Use a multiprocess env runner (one OS process per env). "
                            "Big speedup when env-stepping is the bottleneck.")
    p_pre.add_argument("--years-per-config", type=int, default=5,
                       help="Train this many simulated years on each generated "
                            "facility config before sampling a new one (default: 5).")

    # finetune
    p_ft = sub.add_parser("finetune", help="Fine-tune from a foundation checkpoint.")
    p_ft.add_argument("--config", required=True,
                      help="Path to facility YAML config.")
    p_ft.add_argument("--base", required=True,
                      help="Path to the foundation checkpoint (.pt).")
    p_ft.add_argument("--output", default="clark/data/checkpoints/finetuned.pt",
                      help="Output path for fine-tuned checkpoint.")
    p_ft.add_argument("--episodes", type=int, default=500,
                      help="Number of fine-tuning episodes (default: 500).")
    p_ft.add_argument("--lr", type=float, default=5e-5,
                      help="Learning rate (default: 5e-5).")
    p_ft.add_argument("--freeze-encoder", action="store_true",
                      help="Freeze encoder layers (prevents catastrophic forgetting).")

    # plan
    p_plan = sub.add_parser("plan", help="Generate a shift plan using a trained model.")
    p_plan.add_argument("--config", required=True,
                        help="Path to facility YAML config.")
    p_plan.add_argument("--model", required=True,
                        help="Path to model checkpoint (.pt).")
    p_plan.add_argument("--date", default=None,
                        help="Start date in YYYY-MM-DD format (default: today).")
    p_plan.add_argument("--days", type=int, default=1,
                        help="Number of days to plan ahead (default: 1).")

    # dashboard
    p_dash = sub.add_parser("dashboard", help="Launch the Clark training dashboard.")
    p_dash.add_argument("--log-dir", default="clark/data/logs/pretrain",
                        help="Directory containing episode_log.json / year_snapshot.json.")
    p_dash.add_argument("--port", type=int, default=8080,
                        help="Port to serve the dashboard on (default: 8080).")

    # wizard
    p_wiz = sub.add_parser("wizard", help="Launch the facility setup wizard (web UI).")
    p_wiz.add_argument("--port", type=int, default=8090,
                       help="Port to serve the wizard on (default: 8090).")
    p_wiz.add_argument("--sessions-dir", default="clark/data/configs/user/sessions",
                       help="Directory for saved wizard sessions.")

    p_srv = sub.add_parser("serve", help="Run the minimal local Clark inference API (localhost only).")
    p_srv.add_argument("--model", required=True,
                       help="Path to a trained Clark checkpoint (.pt).")
    p_srv.add_argument("--facilities-dir", default="clark/data/configs",
                       help="Directory of facility config YAMLs to serve.")
    p_srv.add_argument("--port", type=int, default=8000,
                       help="Port (bound to 127.0.0.1 only; default 8000).")

    return parser


# ── Serve (minimal local inference API) ───────────────────────────────────────

def cmd_serve(args: argparse.Namespace):
    """Run the minimal local Clark inference API. Localhost only,
    stateless, weights loaded once. See clark/serve/app.py + NOTE.md."""
    model_path = Path(args.model)
    if not model_path.exists():
        _die(f"Model checkpoint not found: {model_path}")
    fdir = Path(args.facilities_dir)
    if not fdir.is_dir():
        _die(f"Facilities dir not found: {fdir}")

    try:
        from clark.agent.ppo import ClarkAgent
        agent = ClarkAgent.load(str(model_path))      # weights loaded ONCE
    except Exception as e:
        _die(f"Failed to load model: {e}")

    try:
        import uvicorn
        from clark.serve.app import build_app
    except ImportError:
        _die("serve deps missing — install with: pip install -e \".[serve]\"")

    app = build_app(agent, fdir, checkpoint_label=model_path.name)
    print(f"Clark local inference API → http://127.0.0.1:{args.port}  "
          f"(facilities: {fdir}, model: {model_path.name})", flush=True)
    # 127.0.0.1 ONLY — never 0.0.0.0. Local single-user by design.
    uvicorn.run(app, host="127.0.0.1", port=args.port, log_level="info")


# ── Wizard ────────────────────────────────────────────────────────────────────

def cmd_wizard(args: argparse.Namespace):
    """Launch the facility setup wizard — a local web UI that walks
    a warehouse operator through fine-tune config creation.

    Endpoints:
      GET  /                 — wizard HTML
      GET  /presets          — archetype + question library JSON
      GET  /sessions         — list saved sessions
      GET  /sessions/{id}    — load one session
      POST /sessions         — create or update a session
      POST /validate         — defensive validation on the combined config
    """
    _header()

    import http.server
    import json as _json
    import os
    import threading
    import uuid
    import webbrowser
    from datetime import datetime, timezone
    from urllib.parse import urlparse

    wizard_dir = Path(__file__).parent.parent / "clark" / "wizard"
    index_html = wizard_dir / "index.html"
    presets_path = wizard_dir / "presets.json"
    sessions_dir = Path(args.sessions_dir).resolve()
    port = args.port

    if not index_html.exists():
        _die(f"Wizard HTML not found at {index_html}")
    if not presets_path.exists():
        _die(f"Wizard presets not found at {presets_path}")

    sessions_dir.mkdir(parents=True, exist_ok=True)

    # Pre-load presets at startup to fail fast on JSON errors.
    try:
        _presets = _json.loads(presets_path.read_text(encoding="utf-8"))
    except Exception as e:
        _die(f"Failed to parse presets.json: {e}")

    def _validate_config(cfg: dict) -> dict:
        """Defensive validation — walk validation_rules from presets.json
        and report errors/warnings on the combined config. Pure Python,
        no external deps.

        The user explicitly asked for this safety net: combinations of
        preset answers can produce weird weight combos (e.g. OT-cost
        dominating shipping reward → agent prefers leaving orders unshipped).
        These rules catch those before fine-tuning burns hours.
        """
        weights = cfg.get("resulting_weights", {}) or {}
        issues = []

        for rule in _presets.get("validation_rules", []):
            check = rule.get("check")
            level = rule.get("level", "warning")
            msg = rule.get("message", "")

            if check == "per_order_shipped_gt_zero":
                if weights.get("per_order_shipped", 0) <= 0:
                    issues.append({"level": level, "rule": rule["id"], "message": msg})

            elif check == "ot_cost_vs_incomplete":
                ot_hr = abs(weights.get("per_ot_hour", 0))
                inc_pen = abs(weights.get("per_order_incomplete", 0))
                # Heuristic: if 1 hour of OT costs > 0.5x a single incomplete order,
                # the agent will sometimes prefer leaving orders incomplete.
                # The 0.5 factor is conservative — adjust based on observed behavior.
                if inc_pen > 0 and ot_hr > inc_pen * 0.5:
                    issues.append({"level": level, "rule": rule["id"], "message": msg})

            elif check == "idle_not_negative":
                if weights.get("per_idle_hour", 0) >= 0:
                    issues.append({"level": level, "rule": rule["id"], "message": msg})

            elif check == "any_weight_extreme":
                extreme = [(k, v) for k, v in weights.items() if abs(v) > 500]
                if extreme:
                    detail = ", ".join(f"{k}={v}" for k, v in extreme)
                    issues.append({
                        "level": level, "rule": rule["id"],
                        "message": f"{msg} Flagged: {detail}",
                    })

        return {"issues": issues, "checked": len(_presets.get("validation_rules", []))}

    # Roots used by generate + train endpoints
    repo_root = Path(__file__).parent.parent.resolve()
    user_configs_dir = repo_root / "clark" / "data" / "configs" / "user"
    user_checkpoints_dir = repo_root / "clark" / "data" / "checkpoints" / "user"
    user_logs_dir = repo_root / "clark" / "data" / "logs" / "user"
    user_configs_dir.mkdir(parents=True, exist_ok=True)
    user_checkpoints_dir.mkdir(parents=True, exist_ok=True)
    user_logs_dir.mkdir(parents=True, exist_ok=True)

    # In-process registry of training jobs spawned via /train/start.
    # Maps job_id → {pid, config_path, log_dir, started_at}.
    # Lost on server restart by design — training itself is durable
    # (checkpoint + log files on disk) and can be re-attached via the
    # dashboard pointing at log_dir.
    training_jobs: dict = {}

    def _safe_filename(name: str) -> str:
        """Slugify a facility name into a filesystem-safe stem."""
        cleaned = "".join(c if c.isalnum() or c in ("-", "_") else "_"
                          for c in name.strip().lower().replace(" ", "_"))
        return cleaned.strip("_") or "facility"

    def _generate_yaml(cfg: dict) -> dict:
        """Materialize a full FacilityConfig YAML from the wizard's
        archetype + answers. Strategy: load the archetype's base
        template, mutate facility.name and rewards, write to disk under
        clark/data/configs/user/, return path + serialized content.

        The base template carries everything the schema requires
        (workers, volume, tasks, business rules) — for the prototype we
        only override the facility name and reward weights. Later
        wizard steps (worker roster, volume profile) will override
        more of the template.
        """
        import yaml as _yaml

        arch_id = cfg.get("archetype")
        arch = next((a for a in _presets["archetypes"] if a["id"] == arch_id), None)
        if arch is None:
            raise ValueError(f"Unknown archetype: {arch_id!r}")

        template_path = repo_root / arch["base_template"]
        if not template_path.exists():
            raise FileNotFoundError(f"Base template not found: {template_path}")

        base = _yaml.safe_load(template_path.read_text(encoding="utf-8"))
        if not isinstance(base, dict):
            raise ValueError(f"Base template is not a mapping: {template_path}")

        # Override facility name
        facility_name = (cfg.get("facility_name") or "").strip() or "Untitled Facility"
        base.setdefault("facility", {})["name"] = facility_name

        # Merge user-tuned reward weights on top of whatever the template
        # had (rewards: {} in current templates, but we don't assume that).
        weights = cfg.get("resulting_weights") or {}
        merged_rewards = dict(base.get("rewards") or {})
        merged_rewards.update(weights)
        base["rewards"] = merged_rewards

        # Volume profile translation. The wizard collects per-intensity
        # actual ranges (e.g. slow=[60,100], normal=[200,300], peak=[300,440])
        # because real warehouses have asymmetric variance that doesn't fit
        # a single avg × multiplier formula. We map each month's intensity
        # bucket to its corresponding range. If the wizard didn't collect a
        # volume profile (older session, incomplete walkthrough), the
        # template's volume stays intact.
        vol = cfg.get("volume_profile") or {}
        season_ranges = vol.get("season_ranges") or {}

        def _bucket_range(bucket: str) -> tuple[int, int] | None:
            r = season_ranges.get(bucket) or {}
            lo, hi = r.get("low"), r.get("high")
            if not isinstance(lo, (int, float)) or not isinstance(hi, (int, float)):
                return None
            if lo <= 0 or hi <= 0 or hi < lo:
                return None
            return (int(round(float(lo))), int(round(float(hi))))

        normal_range = _bucket_range("normal")
        if normal_range is not None:
            slow_range = _bucket_range("slow") or normal_range
            peak_range = _bucket_range("peak") or normal_range
            band_map = {"slow": slow_range, "normal": normal_range, "peak": peak_range}
            month_intensity = vol.get("month_intensity") or {}
            seasonal = {}
            for m in ["january", "february", "march", "april", "may", "june",
                      "july", "august", "september", "october", "november", "december"]:
                bucket = month_intensity.get(m, "normal")
                lo, hi = band_map.get(bucket, normal_range)
                seasonal[m] = [lo, hi]
            base.setdefault("volume", {})["seasonal_ranges"] = seasonal

            # Weekly curve. The schema stores per-day low/high fractions of
            # the seasonal baseline. Build a peaked-or-flat curve depending
            # on the user's busiest_weekday choice. "none" → flat across the
            # week; otherwise the chosen day gets the maximum range and
            # adjacent days taper off — mirrors a real Mon-heavy or Fri-heavy
            # warehouse pattern.
            weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday"]
            busiest = (vol.get("busiest_weekday") or "none").lower()
            if busiest == "none" or busiest not in weekdays:
                # Flat — same fraction every weekday
                weekly = {d: [0.50, 1.00] for d in weekdays}
            else:
                # Peaked: busiest day = [0.80, 1.00], decreasing by ~0.15
                # per day of distance, floored at [0.10, 0.30].
                idx = weekdays.index(busiest)
                weekly = {}
                for j, d in enumerate(weekdays):
                    dist = abs(j - idx)
                    lo = max(0.10, 0.80 - 0.15 * dist)
                    hi = max(0.30, 1.00 - 0.15 * dist)
                    weekly[d] = [round(lo, 2), round(hi, 2)]
            base.setdefault("volume", {})["weekly_curve"] = weekly

        # Write to disk
        stem = _safe_filename(facility_name)
        out_path = user_configs_dir / f"{stem}.yaml"
        # If a config already exists for this facility name, version it
        # rather than silently overwriting (warehouses iterate).
        if out_path.exists():
            i = 2
            while (user_configs_dir / f"{stem}_v{i}.yaml").exists():
                i += 1
            out_path = user_configs_dir / f"{stem}_v{i}.yaml"

        yaml_text = _yaml.safe_dump(base, sort_keys=False, default_flow_style=False)
        out_path.write_text(yaml_text, encoding="utf-8")

        return {
            "facility_name": facility_name,
            "yaml_path": str(out_path),
            "yaml_text": yaml_text,
        }

    def _start_training(yaml_path: str) -> dict:
        """Spawn cmd_finetune as a detached subprocess. Returns a job_id
        that future /train/{id}/status calls can use.

        Uses the existing CLI entry point so we get all the same defaults
        + validation as a manual `clark finetune` run. The subprocess's
        stdout/stderr stream to a per-job log file so a wizard progress
        view can tail it later.
        """
        import subprocess as _sp
        import uuid as _uuid

        if not Path(yaml_path).exists():
            raise FileNotFoundError(f"Config YAML missing: {yaml_path}")

        job_id = str(_uuid.uuid4())
        job_log_dir = user_logs_dir / job_id
        job_log_dir.mkdir(parents=True, exist_ok=True)
        stem = Path(yaml_path).stem
        ckpt_path = user_checkpoints_dir / f"{stem}.pt"
        base_model = repo_root / "clark" / "data" / "checkpoints" / "clark_foundation.pt"

        if not base_model.exists():
            raise FileNotFoundError(
                f"Foundation checkpoint not found at {base_model}. "
                "Run `clark pretrain` first or download a foundation model."
            )

        stdout_log = open(job_log_dir / "stdout.log", "wb")
        # NOTE: cmd_finetune doesn't currently expose --log-dir, so finetune
        # defaults the log dir to a sibling of --output. The job_log_dir we
        # create above just holds the subprocess stdout for the wizard's
        # progress view; the real episode logs live next to the checkpoint.
        cmd = [
            sys.executable, "-m", "cli.main", "finetune",
            "--config", str(yaml_path),
            "--base", str(base_model),
            "--output", str(ckpt_path),
        ]
        proc = _sp.Popen(cmd, cwd=str(repo_root), stdout=stdout_log,
                         stderr=_sp.STDOUT)
        training_jobs[job_id] = {
            "pid": proc.pid,
            "config_path": yaml_path,
            "log_dir": str(job_log_dir),
            "checkpoint_path": str(ckpt_path),
            "started_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        }
        return {"job_id": job_id, **training_jobs[job_id]}

    def _list_sessions() -> list[dict]:
        out = []
        for p in sorted(sessions_dir.glob("*.json")):
            try:
                data = _json.loads(p.read_text(encoding="utf-8"))
                out.append({
                    "session_id": data.get("session_id", p.stem),
                    "facility_name": data.get("facility_name", "(unnamed)"),
                    "updated_at": data.get("updated_at", ""),
                })
            except Exception:
                continue
        # Most recently updated first
        out.sort(key=lambda s: s.get("updated_at", ""), reverse=True)
        return out

    class WizardHandler(http.server.BaseHTTPRequestHandler):
        def log_message(self, fmt, *a):
            pass  # suppress default access log spam

        def do_GET(self):
            path = urlparse(self.path).path
            if path in ("/", "/index.html"):
                # Re-read each request so editing the HTML during dev
                # takes effect on browser refresh without a server restart.
                self._send(200, "text/html; charset=utf-8", index_html.read_bytes())
            elif path == "/presets":
                self._send(200, "application/json", presets_path.read_bytes())
            elif path == "/sessions":
                payload = {"sessions": _list_sessions()}
                self._send(200, "application/json",
                           _json.dumps(payload).encode("utf-8"))
            elif path.startswith("/sessions/"):
                sid = path[len("/sessions/"):]
                fpath = sessions_dir / f"{sid}.json"
                if not fpath.exists():
                    self._send(404, "application/json",
                               b'{"error":"session not found"}')
                    return
                self._send(200, "application/json", fpath.read_bytes())
            elif path.startswith("/train/") and path.endswith("/status"):
                # GET /train/{job_id}/status — poll subprocess liveness.
                job_id = path[len("/train/"):-len("/status")]
                job = training_jobs.get(job_id)
                if job is None:
                    self._send(404, "application/json",
                               b'{"error":"unknown job id"}')
                    return
                # Liveness check: psutil-free, just kill 0 the pid.
                alive = True
                try:
                    os.kill(job["pid"], 0)
                except (OSError, ProcessLookupError):
                    alive = False
                payload = {**job, "alive": alive}
                self._send(200, "application/json",
                           _json.dumps(payload).encode("utf-8"))
            else:
                self._send(404, "text/plain", b"Not found")

        def do_POST(self):
            path = urlparse(self.path).path
            length = int(self.headers.get("Content-Length", 0))
            raw = self.rfile.read(length) if length else b"{}"
            try:
                body = _json.loads(raw)
            except Exception:
                self._send(400, "application/json", b'{"error":"invalid JSON"}')
                return

            if path == "/sessions":
                sid = body.get("session_id") or str(uuid.uuid4())
                now = datetime.now(timezone.utc).isoformat(timespec="seconds")
                fpath = sessions_dir / f"{sid}.json"
                created_at = now
                if fpath.exists():
                    try:
                        existing = _json.loads(fpath.read_text(encoding="utf-8"))
                        created_at = existing.get("created_at", now)
                    except Exception:
                        pass
                doc = {
                    "session_id": sid,
                    "facility_name": body.get("facility_name", ""),
                    "selected_archetype": body.get("selected_archetype"),
                    "season_ranges": body.get("season_ranges", {}),
                    "month_intensity": body.get("month_intensity", {}),
                    "busiest_weekday": body.get("busiest_weekday"),
                    "answers": body.get("answers", {}),
                    "current_step": body.get("current_step", 0),
                    "created_at": created_at,
                    "updated_at": now,
                }
                fpath.write_text(_json.dumps(doc, indent=2), encoding="utf-8")
                self._send(200, "application/json",
                           _json.dumps({"session_id": sid, "saved_at": now}).encode("utf-8"))

            elif path == "/validate":
                result = _validate_config(body)
                self._send(200, "application/json",
                           _json.dumps(result).encode("utf-8"))

            elif path == "/generate":
                # Materialize the YAML from archetype + answers.
                # Returns yaml_text (for preview) and yaml_path (on disk).
                try:
                    result = _generate_yaml(body)
                    self._send(200, "application/json",
                               _json.dumps(result).encode("utf-8"))
                except Exception as e:
                    self._send(400, "application/json",
                               _json.dumps({"error": str(e)}).encode("utf-8"))

            elif path == "/train/start":
                # Body: {"yaml_path": "..."}  — kicks off finetune subprocess.
                # Foundation checkpoint must already exist; we don't auto-pretrain.
                yaml_path = body.get("yaml_path")
                if not yaml_path:
                    self._send(400, "application/json",
                               b'{"error":"yaml_path required"}')
                    return
                try:
                    result = _start_training(yaml_path)
                    self._send(200, "application/json",
                               _json.dumps(result).encode("utf-8"))
                except Exception as e:
                    self._send(400, "application/json",
                               _json.dumps({"error": str(e)}).encode("utf-8"))

            else:
                self._send(404, "text/plain", b"Not found")

        def _send(self, code: int, ctype: str, body: bytes):
            self.send_response(code)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(body)

    server = http.server.HTTPServer(("localhost", port), WizardHandler)
    url = f"http://localhost:{port}"
    print(f"  Wizard:       {url}")
    print(f"  Sessions dir: {sessions_dir}")
    print(f"  Press Ctrl+C to stop.\n")

    def _open():
        import time as _time
        _time.sleep(0.5)
        webbrowser.open(url)
    threading.Thread(target=_open, daemon=True).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nWizard stopped.")


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    parser = build_parser()
    args = parser.parse_args()

    dispatch = {
        "init":      cmd_init,
        "validate":  cmd_validate,
        "pretrain":  cmd_pretrain,
        "finetune":  cmd_finetune,
        "plan":      cmd_plan,
        "dashboard": cmd_dashboard,
        "wizard":    cmd_wizard,
        "serve":     cmd_serve,
    }

    fn = dispatch.get(args.command)
    if fn is None:
        parser.print_help()
        sys.exit(1)

    fn(args)


# Allow direct invocation: python cli/main.py <command>
app = main  # pyproject.toml entry point: clark = "cli.main:app"

if __name__ == "__main__":
    main()
